-- Generated by outlass 0.1.0 from src/client_shared/theme.scss. Do not edit by hand.

local sheet = Instance.new("StyleSheet")
sheet.Name = "theme"
sheet:SetAttribute("Void", Color3.fromRGB(8, 11, 15))
sheet:SetAttribute("Steel", Color3.fromRGB(20, 26, 34))
sheet:SetAttribute("SteelRaised", Color3.fromRGB(31, 40, 51))
sheet:SetAttribute("SteelLit", Color3.fromRGB(52, 66, 82))
sheet:SetAttribute("Edge", Color3.fromRGB(78, 96, 118))
sheet:SetAttribute("Text", Color3.fromRGB(236, 244, 252))
sheet:SetAttribute("TextDim", Color3.fromRGB(186, 202, 220))
sheet:SetAttribute("TextFaint", Color3.fromRGB(146, 166, 188))
sheet:SetAttribute("Metal", Color3.fromRGB(196, 206, 220))
sheet:SetAttribute("Energy", Color3.fromRGB(255, 230, 64))
sheet:SetAttribute("Buildpower", Color3.fromRGB(126, 240, 154))
sheet:SetAttribute("Gain", Color3.fromRGB(96, 224, 128))
sheet:SetAttribute("Danger", Color3.fromRGB(238, 88, 74))
sheet:SetAttribute("Caution", Color3.fromRGB(236, 184, 68))
sheet:SetAttribute("Accent", Color3.fromRGB(96, 210, 242))
sheet:SetAttribute("Resurrect", Color3.fromRGB(176, 96, 240))
sheet:SetAttribute("Fight", Color3.fromRGB(255, 138, 64))
sheet:SetAttribute("Emp", Color3.fromRGB(130, 215, 255))
sheet:SetAttribute("Disintegrator", Color3.fromRGB(238, 60, 48))
sheet:SetAttribute("Guard", Color3.fromRGB(190, 150, 255))
sheet:SetAttribute("TierCommon", Color3.fromRGB(178, 190, 204))
sheet:SetAttribute("TierUncommon", Color3.fromRGB(110, 222, 96))
sheet:SetAttribute("TierRare", Color3.fromRGB(96, 210, 242))
sheet:SetAttribute("TierEpic", Color3.fromRGB(176, 96, 240))
sheet:SetAttribute("TierLegendary", Color3.fromRGB(255, 196, 64))
sheet:SetAttribute("TierMythic", Color3.fromRGB(255, 98, 74))

local function rule(parent: Instance, selector: string, priority: number?, properties: { [string]: any }?): StyleRule
	local r = Instance.new("StyleRule")
	r.Name = selector
	r.Selector = selector
	if priority then
		r.Priority = priority
	end
	if properties then
		r:SetProperties(properties)
	end
	r.Parent = parent
	return r
end

rule(sheet, "TextLabel, TextButton, TextBox", 0, {
	RichText = true,
	TextWrapped = true,
})

rule(sheet, "ScrollingFrame", 0, {
	AutomaticCanvasSize = Enum.AutomaticSize.XY,
	CanvasSize = UDim2.new(),
})

rule(sheet, "Frame, TextLabel, TextButton, TextBox, ImageLabel, ImageButton, ScrollingFrame, CanvasGroup, VideoFrame, ViewportFrame", 0, {
	AutomaticSize = Enum.AutomaticSize.XY,
})

return sheet
