"""Uploads the synthesized sounds to Roblox as Audio assets and writes their ids into src/client/sound_ids.luau.

    python tools/sound_pipeline/synth.py
    python tools/sound_pipeline/upload_sounds.py --creator-type User --creator-id 123456 [name ...]

With no names it goes through every build/<name>.ogg. A sound whose file has not changed since it was last uploaded
(uploads.json keeps the hash of each one's .wav) is skipped. Nothing is uploaded that has not been listened to and
approved as it is built now (review.py); a copy of each upload is kept in build/uploaded for the next review.

The API key is read from $ROBLOX_API_KEY, --api-key, or rbxopencloudkey.txt at the repo root, and needs asset:read
and asset:write for the creator.
"""

import argparse
import hashlib
import json
import os
import shutil
import sys
import time
from pathlib import Path

import requests

PIPELINE = Path(__file__).resolve().parent
REPO = PIPELINE.parent.parent
BUILD = PIPELINE / "build"
UPLOADS_PATH = PIPELINE / "uploads.json"
APPROVED_PATH = PIPELINE / "approved.json"
UPLOADED = BUILD / "uploaded"
LUAU_PATH = REPO / "src" / "client" / "sound_ids.luau"
ASSETS_URL = "https://apis.roblox.com/assets/v1/assets"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("names", nargs="*")
    parser.add_argument("--creator-type", choices=["User", "Group"], required=True)
    parser.add_argument("--creator-id", required=True)
    parser.add_argument("--api-key", default=None)
    parser.add_argument("--poll-seconds", type=float, default=3.0)
    parser.add_argument("--timeout-seconds", type=float, default=300.0)
    return parser.parse_args()


def api_key(args) -> str:
    if args.api_key:
        return args.api_key
    if os.environ.get("ROBLOX_API_KEY"):
        return os.environ["ROBLOX_API_KEY"]
    path = REPO / "rbxopencloudkey.txt"
    if path.is_file():
        return path.read_text(encoding="utf-8").strip()
    sys.exit("no API key: pass --api-key, set ROBLOX_API_KEY, or put it in rbxopencloudkey.txt")


def upload(path: Path, args, key: str) -> str:
    request = {
        "assetType": "Audio",
        "displayName": f"rts_{path.stem}",
        "description": "Synthesized by tools/sound_pipeline/synth.py",
        "creationContext": {
            "creator": {("userId" if args.creator_type == "User" else "groupId"): str(args.creator_id)}
        },
    }
    with path.open("rb") as file:
        response = requests.post(
            ASSETS_URL,
            headers={"x-api-key": key},
            data={"request": json.dumps(request)},
            files={"fileContent": (path.name, file, "audio/ogg")},
        )
    if not response.ok:
        sys.exit(f"{path.name}: {response.status_code} {response.text}")
    operation_path = response.json()["path"]
    deadline = time.time() + args.timeout_seconds
    while time.time() < deadline:
        status = requests.get(f"https://apis.roblox.com/assets/v1/{operation_path}", headers={"x-api-key": key})
        status.raise_for_status()
        body = status.json()
        if body.get("done"):
            if "error" in body:
                sys.exit(f"{path.name}: upload failed: {body['error']}")
            return str(body["response"]["assetId"])
        time.sleep(args.poll_seconds)
    sys.exit(f"{path.name}: timed out waiting for Roblox to process the upload")


def write_luau(uploads: dict):
    lines = [
        "-- Generated by tools/sound_pipeline/upload_sounds.py: the uploaded asset id of each synthesized sound.",
        "",
        "return table.freeze({",
    ]
    for name in sorted(uploads):
        lines.append(f'\t{name} = "rbxassetid://{uploads[name]["id"]}",')
    lines.append("})")
    LUAU_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main():
    args = parse_args()
    key = api_key(args)
    uploads = json.loads(UPLOADS_PATH.read_text()) if UPLOADS_PATH.is_file() else {}
    approved = json.loads(APPROVED_PATH.read_text()) if APPROVED_PATH.is_file() else {}
    names = args.names or sorted(path.stem for path in BUILD.glob("*.ogg"))
    for name in names:
        path = BUILD / f"{name}.ogg"
        if not path.is_file():
            sys.exit(f"no {path}: run synth.py first")
        # the .wav, not the .ogg: the encoder stamps each .ogg with a random stream serial
        digest = hashlib.sha256(path.with_suffix(".wav").read_bytes()).hexdigest()
        if uploads.get(name, {}).get("sha256") == digest:
            print(f"{name}: unchanged ({uploads[name]['id']})")
            continue
        if approved.get(name) != digest:
            sys.exit(f"{name}: not approved as built now; listen with review.py, then `review.py approve {name}`")
        asset_id = upload(path, args, key)
        UPLOADED.mkdir(exist_ok=True)
        shutil.copyfile(path, UPLOADED / path.name)
        shutil.copyfile(path.with_suffix(".wav"), UPLOADED / f"{name}.wav")
        uploads[name] = {"id": asset_id, "sha256": digest}
        UPLOADS_PATH.write_text(json.dumps(uploads, indent=2) + "\n", newline="\n")
        print(f"{name}: {asset_id}")
    write_luau(uploads)


if __name__ == "__main__":
    main()
