"""Uploads the synthesized sounds to Roblox as Audio assets and writes their ids into src/client_shared/sound_ids.luau.

    python tools/sound_pipeline/synth.py
    python tools/sound_pipeline/upload_sounds.py [name ...]
    python tools/sound_pipeline/upload_sounds.py --write-ids   # only rewrite sound_ids.luau from uploads.json

With no names it goes through every build/<name>.ogg. A sound whose file has not changed since it was last uploaded
(uploads.json keeps the hash of each one's .wav) is skipped. Nothing is uploaded that has not been listened to and
approved as it is built now (review.py); a copy of each upload is kept in build/uploaded for the next review.

The key and the creator are tools/roblox_open_cloud.py's.
"""

import argparse
import shutil
import sys
from pathlib import Path

from records import BUILD, PIPELINE, UPLOADED, UPLOADS_PATH, digest, load_approved

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import roblox_open_cloud  # noqa: E402

LUAU_PATH = PIPELINE.parent.parent / "src" / "client_shared" / "sound_ids.luau"


def write_luau(sounds: dict):
    lines = [
        "-- Generated by tools/sound_pipeline/upload_sounds.py: the uploaded asset id of each synthesized sound.",
        "",
        "return table.freeze({",
    ]
    for name in sorted(sounds):
        lines.append(f'\t{name} = "rbxassetid://{sounds[name]["id"]}",')
    lines.append("})")
    LUAU_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("names", nargs="*")
    parser.add_argument("--write-ids", action="store_true", help="only rewrite sound_ids.luau from uploads.json")
    roblox_open_cloud.add_key_argument(parser)
    args = parser.parse_args()

    store = roblox_open_cloud.load_store(UPLOADS_PATH)
    sounds = store["assets"]
    if args.write_ids:
        write_luau(sounds)
        return
    approved = load_approved()
    names = args.names or sorted(path.stem for path in BUILD.glob("*.ogg"))
    key = None
    for name in names:
        path = BUILD / f"{name}.ogg"
        if not path.is_file():
            sys.exit(f"no {path}: run synth.py first")
        built = digest(name)
        if sounds.get(name, {}).get("sha256") == built:
            print(f"{name}: unchanged ({sounds[name]['id']})")
            continue
        if approved.get(name) != built:
            sys.exit(f"{name}: not approved as built now; listen with review.py, then `review.py approve {name}`")
        key = key or roblox_open_cloud.api_key(args.api_key)
        asset_id = roblox_open_cloud.upload(
            path, "Audio", "audio/ogg", f"rts_{name}", "Synthesized by tools/sound_pipeline/synth.py", key
        )
        UPLOADED.mkdir(exist_ok=True)
        shutil.copyfile(path, UPLOADED / path.name)
        shutil.copyfile(path.with_suffix(".wav"), UPLOADED / f"{name}.wav")
        sounds[name] = {"id": asset_id, "sha256": built}
        roblox_open_cloud.save_store(UPLOADS_PATH, store)
        print(f"{name}: {asset_id}")
    write_luau(sounds)


if __name__ == "__main__":
    main()
