-- Generated by outlass 0.1.0 from src/client/ui/stylesheets/default.scss. Do not edit by hand.

local sheet = Instance.new("StyleSheet")
sheet.Name = "default"
sheet:SetAttribute("Void", Color3.fromRGB(8, 11, 15))
sheet:SetAttribute("Steel", Color3.fromRGB(20, 26, 34))
sheet:SetAttribute("SteelRaised", Color3.fromRGB(31, 40, 51))
sheet:SetAttribute("SteelLit", Color3.fromRGB(52, 66, 82))
sheet:SetAttribute("Edge", Color3.fromRGB(78, 96, 118))
sheet:SetAttribute("Text", Color3.fromRGB(236, 244, 252))
sheet:SetAttribute("TextDim", Color3.fromRGB(186, 202, 220))
sheet:SetAttribute("TextFaint", Color3.fromRGB(146, 166, 188))
sheet:SetAttribute("Metal", Color3.fromRGB(196, 206, 220))
sheet:SetAttribute("Energy", Color3.fromRGB(255, 230, 64))
sheet:SetAttribute("Buildpower", Color3.fromRGB(126, 240, 154))
sheet:SetAttribute("Gain", Color3.fromRGB(96, 224, 128))
sheet:SetAttribute("Danger", Color3.fromRGB(238, 88, 74))
sheet:SetAttribute("Accent", Color3.fromRGB(96, 210, 242))
sheet:SetAttribute("Resurrect", Color3.fromRGB(176, 96, 240))
sheet:SetAttribute("Fight", Color3.fromRGB(255, 138, 64))

local function rule(parent: Instance, selector: string, priority: number?, properties: { [string]: any }?): StyleRule
	local r = Instance.new("StyleRule")
	r.Name = selector
	r.Selector = selector
	if priority then
		r.Priority = priority
	end
	if properties then
		r:SetProperties(properties)
	end
	r.Parent = parent
	return r
end

rule(sheet, "TextLabel, TextButton, TextBox", 0, {
	RichText = true,
	TextWrapped = true,
})

rule(sheet, "Frame, TextLabel, TextButton, TextBox, ImageLabel, ImageButton, ScrollingFrame, CanvasGroup, VideoFrame, ViewportFrame", 0, {
	AutomaticSize = Enum.AutomaticSize.XY,
})

rule(sheet, "Frame, TextButton, TextLabel", 1, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
})

rule(sheet, "Frame::UIStroke, TextButton::UIStroke, TextLabel::UIStroke", 1, {
	Enabled = false,
})

rule(sheet, "TextLabel, TextButton", 2, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Center,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".panel", 3, {
	TextTransparency = 0.03,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.03,
	ImageTransparency = 0.03,
	GroupTransparency = 0.03,
})

rule(sheet, ".panel::UIGradient", 3, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.03, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.04, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(0.55, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(1, Color3.fromRGB(1, 1, 2))}),
	Rotation = 90,
})

rule(sheet, ".panel::UIPadding", 3, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".rail", 4, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 2),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".rail::UIGradient", 4, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(0.55, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(0.55, 0), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 0,
})

rule(sheet, ".hazard, .build-option.unaffordable", 91, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".hazard::UIGradient, .build-option.unaffordable::UIGradient", 91, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.12, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.12, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.25, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.25, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.37, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.37, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.5, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.5, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.62, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.62, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.75, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.75, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.87, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.87, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(1, Color3.fromRGB(8, 11, 15))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.1), NumberSequenceKeypoint.new(0.12, 0.1), NumberSequenceKeypoint.new(0.25, 0.1), NumberSequenceKeypoint.new(0.37, 0.1), NumberSequenceKeypoint.new(0.5, 0.1), NumberSequenceKeypoint.new(0.62, 0.1), NumberSequenceKeypoint.new(0.75, 0.1), NumberSequenceKeypoint.new(0.87, 0.1), NumberSequenceKeypoint.new(1, 0.1)}),
	Rotation = -45,
})

rule(sheet, ".faint", 5, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
})

rule(sheet, ".metal", 6, {
	TextColor3 = "$Metal",
	TextTransparency = 0,
})

rule(sheet, ".energy", 7, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
})

rule(sheet, ".accent", 8, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
})

rule(sheet, ".heading, .selection-name", 9, {
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".heading::UIStroke, .selection-name::UIStroke", 9, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.15,
})

rule(sheet, ".readout, .resource-amount, .wind-speed, .scavenger-value", 10, {
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".readout::UIStroke, .resource-amount::UIStroke, .wind-speed::UIStroke, .scavenger-value::UIStroke", 10, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.2,
})

rule(sheet, ".grow::UIFlexItem", 11, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".resource-bar", 12, {
	TextTransparency = 0.03,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.03,
	ImageTransparency = 0.03,
	GroupTransparency = 0.03,
	Size = UDim2.new(0, 780, 0, 76),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0.5, 0, 0, 0),
	AnchorPoint = Vector2.new(0.5, 0),
})

rule(sheet, ".resource-bar::UIGradient", 12, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.03, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.04, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(0.55, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(1, Color3.fromRGB(1, 1, 2))}),
	Rotation = 90,
})

rule(sheet, ".resource-bar::UIPadding", 12, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 28),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 28),
})

rule(sheet, ".resource-bar::UIListLayout", 12, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 24),
})

rule(sheet, ".resource-bar.with-scavengers", 92, {
	Size = UDim2.new(0, 960, 0, 76),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".resource", 13, {
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".resource::UIListLayout", 13, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	ItemLineAlignment = Enum.ItemLineAlignment.Stretch,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".resource::UIFlexItem", 13, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".resource-chip", 14, {
	Size = UDim2.new(0, 4, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".resource-chip.metal-chip", 93, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".resource-chip.metal-chip::UIGradient", 93, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(1, Color3.fromRGB(196, 206, 220))}),
	Rotation = 90,
})

rule(sheet, ".resource-chip.energy-chip", 94, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".resource-chip.energy-chip::UIGradient", 94, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 243, 166)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 230, 64))}),
	Rotation = 90,
})

rule(sheet, ".resource-head", 15, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".resource-head::UIListLayout", 15, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".resource-name", 16, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
})

rule(sheet, ".resource-name::UIFlexItem", 16, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".resource-amount", 17, {
	TextSize = 19,
	TextXAlignment = Enum.TextXAlignment.Right,
})

rule(sheet, ".resource-income", 18, {
	TextColor3 = "$Buildpower",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Right,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".resource-flow", 19, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".resource-flow::UIListLayout", 19, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".resource-revenue", 20, {
	TextColor3 = "$Gain",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".resource-expense", 21, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Right,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".resource-track", 22, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 6),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
	ClipsDescendants = true,
})

rule(sheet, ".resource-track::UIStroke", 22, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(27, 34, 41),
	Transparency = 0,
})

do
	local r1 = rule(sheet, ".resource-fill", 23, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".resource-fill::UIGradient", 23, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(69, 89, 117)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(196, 206, 220)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".resource-fill.energy-fill", 95, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".resource-fill.energy-fill::UIGradient", 95, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(90, 78, 0)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(255, 230, 64)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 247, 192))}),
	Rotation = 0,
})

rule(sheet, ".stalling", 136, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
})

rule(sheet, ".resource-divider", 24, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 2, 0, 44),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".resource-divider::UIGradient", 24, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 0)), ColorSequenceKeypoint.new(0.35, Color3.fromRGB(78, 96, 118)), ColorSequenceKeypoint.new(0.65, Color3.fromRGB(78, 96, 118)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.35, 0), NumberSequenceKeypoint.new(0.65, 0), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 90,
})

rule(sheet, ".wind-block", 25, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.5,
	Size = UDim2.new(0, 130, 0, 64),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".wind-block::UIStroke", 25, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".wind-field", 26, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".wind-content", 27, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".wind-content::UIPadding", 27, {
	PaddingTop = UDim.new(0, 8),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 8),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".wind-content::UIListLayout", 27, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".wind-head", 28, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".wind-head::UIListLayout", 28, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".wind-speed", 29, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 19,
	TextXAlignment = Enum.TextXAlignment.Left,
})

rule(sheet, ".wind-gauge", 30, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.15,
	Size = UDim2.new(1, 0, 0, 5),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
	ClipsDescendants = true,
})

rule(sheet, ".wind-gauge::UIStroke", 30, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(27, 34, 41),
	Transparency = 0,
})

do
	local r1 = rule(sheet, ".wind-gauge-fill", 31, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".wind-gauge-fill::UIGradient", 31, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(8, 80, 100)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(214, 243, 252))}),
	Rotation = 0,
})

rule(sheet, ".wind-range", 32, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".wind-range::UIListLayout", 32, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".wind-limit", 33, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 9,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".wind-limit.right", 96, {
	TextXAlignment = Enum.TextXAlignment.Right,
})

rule(sheet, ".scavenger-block", 34, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.5,
	Size = UDim2.new(0, 130, 0, 64),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".scavenger-block::UIPadding", 34, {
	PaddingTop = UDim.new(0, 8),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 8),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".scavenger-block::UIStroke", 34, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".scavenger-block::UIListLayout", 34, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".scavenger-head", 35, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".scavenger-head::UIListLayout", 35, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".scavenger-value", 36, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
	TextSize = 19,
	TextXAlignment = Enum.TextXAlignment.Left,
})

rule(sheet, ".bottom-left", 37, {
	AutomaticSize = Enum.AutomaticSize.XY,
	Position = UDim2.new(0, 20, 1, -20),
	AnchorPoint = Vector2.new(0, 1),
})

rule(sheet, ".bottom-left::UIListLayout", 37, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Bottom,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".selection-panel", 38, {
	Size = UDim2.new(0, 330, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".selection-panel::UIPadding", 38, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".selection-panel::UIListLayout", 38, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".selection-title", 39, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".selection-title::UIListLayout", 39, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".selection-name::UIFlexItem", 40, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".badge", 41, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 17),
	AutomaticSize = Enum.AutomaticSize.X,
	BorderSizePixel = 0,
})

rule(sheet, ".badge::UIPadding", 41, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".badge::UIStroke", 41, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".badge-blueprint", 42, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".badge-blueprint::UIStroke", 42, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".badge-count", 43, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".badge-count::UIStroke", 43, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".stat-list", 44, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".stat-list::UIListLayout", 44, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".stat", 45, {
	Size = UDim2.new(1, 0, 0, 17),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".stat::UIListLayout", 45, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".stat-label", 46, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
})

rule(sheet, ".stat-label::UIFlexItem", 46, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".stat-value", 47, {
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Right,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".progress-track", 48, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 8),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
	ClipsDescendants = true,
})

rule(sheet, ".progress-track::UIStroke", 48, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(27, 34, 41),
	Transparency = 0,
})

do
	local r1 = rule(sheet, ".progress-fill", 49, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".progress-fill::UIGradient", 49, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(14, 122, 41)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(126, 240, 154)), ColorSequenceKeypoint.new(1, Color3.fromRGB(240, 253, 243))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".progress-fill.blueprint-fill", 97, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".progress-fill.blueprint-fill::UIGradient", 97, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(8, 80, 100)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(214, 243, 252))}),
	Rotation = 0,
})

rule(sheet, ".queue-strip", 50, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".queue-strip::UIListLayout", 50, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
	Wraps = true,
})

do
	local r1 = rule(sheet, ".queue-chip", 51, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		TextSize = 11,
		FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
		Size = UDim2.new(0, 30, 0, 30),
		AutomaticSize = Enum.AutomaticSize.None,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".queue-chip::UIGradient", 51, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".queue-chip::UIStroke", 51, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".queue-chip:Hover", 98, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".queue-chip:Hover::UIStroke", 98, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".queue-chip:Press", 99, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".queue-chip:NonInteractable", 100, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".queue-chip:Hover", 101, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".queue-chip:Hover::UIStroke", 101, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".selection-subtitle", 52, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".build-menu", 53, {
	Size = UDim2.new(0, 336, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
	Position = UDim2.new(1, -20, 1, -20),
	AnchorPoint = Vector2.new(1, 1),
})

rule(sheet, ".build-menu::UIPadding", 53, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".build-menu::UIListLayout", 53, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".build-title", 54, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".build-title::UIListLayout", 54, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".build-grid::UIGridLayout", 55, {
	SortOrder = Enum.SortOrder.LayoutOrder,
	CellPadding = UDim2.new(0, 8, 0, 8),
	FillDirectionMaxCells = 3,
	CellSize = UDim2.new(0, 96, 0, 96),
})

do
	local r1 = rule(sheet, ".build-option", 56, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 96, 0, 96),
		AutomaticSize = Enum.AutomaticSize.None,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".build-option::UIGradient", 56, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".build-option::UIPadding", 56, {
	PaddingTop = UDim.new(0, 8),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 8),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".build-option::UIStroke", 56, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".build-option::UIListLayout", 56, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Bottom,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".build-option:Hover", 102, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".build-option:Hover::UIStroke", 102, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".build-option:Press", 103, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".build-option:NonInteractable", 104, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".build-option.unaffordable", 105, {
	TextTransparency = 0.25,
	BackgroundTransparency = 0.25,
	ImageTransparency = 0.25,
	GroupTransparency = 0.25,
	BorderSizePixel = 0,
})

rule(sheet, ".build-option.unaffordable::UIStroke", 105, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0.25,
})

rule(sheet, ".build-tabs", 57, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".build-tabs::UIListLayout", 57, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

do
	local r1 = rule(sheet, ".build-tab", 58, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 74, 0, 34),
		AutomaticSize = Enum.AutomaticSize.None,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".build-tab::UIGradient", 58, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".build-tab::UIStroke", 58, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".build-tab::UIListLayout", 58, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".build-tab:Hover", 106, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".build-tab:Hover::UIStroke", 106, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".build-tab:Press", 107, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".build-tab:NonInteractable", 108, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".build-tab.active", 109, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".build-tab.active::UIStroke", 109, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".build-tab-name", 59, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 10,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".build-tab-key", 60, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 10,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".build-option-key", 61, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.3,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	AutomaticSize = Enum.AutomaticSize.XY,
	Position = UDim2.new(1, -4, 0, 4),
	AnchorPoint = Vector2.new(1, 0),
	BorderSizePixel = 0,
})

rule(sheet, ".build-option-key::UIPadding", 61, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 4),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".build-option-key::UIStroke", 61, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".build-option-name", 62, {
	TextSize = 14,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".build-cost::UIListLayout", 63, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".cost", 64, {
	TextSize = 13,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".cost-metal", 65, {
	TextColor3 = "$Metal",
	TextTransparency = 0,
})

rule(sheet, ".cost-energy", 66, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
})

rule(sheet, ".build-hint", 67, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".build-option-subtitle", 68, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 12,
})

rule(sheet, ".command-panel", 69, {
	Size = UDim2.new(0, 210, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".command-panel::UIPadding", 69, {
	PaddingTop = UDim.new(0, 12),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 12),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".command-panel::UIListLayout", 69, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".command-title", 70, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".command-title::UIListLayout", 70, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

do
	local r1 = rule(sheet, ".command-row", 71, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(1, 0, 0, 28),
		AutomaticSize = Enum.AutomaticSize.None,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".command-row::UIGradient", 71, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".command-row::UIPadding", 71, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".command-row::UIStroke", 71, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".command-row::UIListLayout", 71, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".command-row:Hover", 110, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".command-row:Hover::UIStroke", 110, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".command-row:Press", 111, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".command-row:NonInteractable", 112, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".command-row.active", 113, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".command-row.active::UIStroke", 113, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".command-name", 72, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
})

rule(sheet, ".command-key", 73, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 13,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".selection-box", 74, {
	BackgroundColor3 = Color3.fromRGB(96, 210, 242),
	BackgroundTransparency = 0.9,
	ZIndex = 100,
	BorderSizePixel = 0,
})

rule(sheet, ".selection-box::UIStroke", 74, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".placement-hint", 75, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.18,
	TextSize = 12,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Position = UDim2.new(0.5, 0, 1, -128),
	AnchorPoint = Vector2.new(0.5, 1),
	BorderSizePixel = 0,
})

rule(sheet, ".placement-hint::UIPadding", 75, {
	PaddingTop = UDim.new(0, 8),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 8),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".placement-hint::UIStroke", 75, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".mode-hint", 76, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".mode-hint::UIStroke", 76, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".mode-hint.attack", 114, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".mode-hint.attack::UIStroke", 114, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".mode-hint.fight", 115, {
	TextColor3 = "$Fight",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".mode-hint.fight::UIStroke", 115, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".mode-hint.repair", 116, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".mode-hint.repair::UIStroke", 116, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".mode-hint.resurrect", 117, {
	TextColor3 = "$Resurrect",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".mode-hint.resurrect::UIStroke", 117, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".world-bar", 77, {
	Size = UDim2.new(0, 52, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
	Interactable = false,
})

rule(sheet, ".world-bar::UIListLayout", 77, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 2),
})

rule(sheet, ".bar-name", 78, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 10,
	TextWrapped = false,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".bar-dot", 79, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 6, 0, 6),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".bar-dot::UICorner", 79, {
	CornerRadius = UDim.new(0.5, 0),
})

rule(sheet, ".bar-dot::UIStroke", 79, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(0, 0, 0),
	Transparency = 0.6,
})

rule(sheet, ".bar-track", 80, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.15,
	Size = UDim2.new(1, 0, 0, 6),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
	ClipsDescendants = true,
})

rule(sheet, ".bar-track::UIStroke", 80, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(27, 34, 41),
	Transparency = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.health", 118, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.health::UIGradient", 118, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(14, 122, 41)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(126, 240, 154)), ColorSequenceKeypoint.new(1, Color3.fromRGB(240, 253, 243))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.health.mid", 130, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.health.mid::UIGradient", 130, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(68, 49, 7)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(236, 184, 68)), ColorSequenceKeypoint.new(1, Color3.fromRGB(248, 228, 184))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.health.low", 131, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.health.low::UIGradient", 131, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(75, 13, 7)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(1, Color3.fromRGB(249, 196, 191))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.progress", 119, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.progress::UIGradient", 119, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(8, 80, 100)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(214, 243, 252))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.reclaim", 120, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.reclaim::UIGradient", 120, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(69, 89, 117)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(196, 206, 220)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.resurrect", 121, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.resurrect::UIGradient", 121, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(58, 9, 97)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(176, 96, 240)), ColorSequenceKeypoint.new(1, Color3.fromRGB(234, 213, 251))}),
	Rotation = 0,
})

rule(sheet, ".world-bar.blueprint >> .bar-track", 132, {
	BorderSizePixel = 0,
})

rule(sheet, ".world-bar.blueprint >> .bar-track::UIStroke", 132, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".bar-eta", 81, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 11,
	TextWrapped = false,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".bar-eta.decaying", 122, {
	TextColor3 = Color3.fromRGB(238, 88, 74),
	TextTransparency = 0,
})

rule(sheet, ".bar-eta.decaying.lit", 133, {
	TextColor3 = Color3.fromRGB(255, 255, 255),
	TextTransparency = 0,
})

rule(sheet, ".bar-warning", 82, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
	TextSize = 11,
	TextWrapped = false,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".bar-warning.lit", 124, {
	TextColor3 = Color3.fromRGB(255, 255, 255),
	TextTransparency = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.reload", 125, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.reload::UIGradient", 125, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(90, 78, 0)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(255, 230, 64)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 247, 192))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.shield", 126, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.shield::UIGradient", 126, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(8, 80, 100)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(214, 243, 252))}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".bar-fill.stockpile", 127, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".bar-fill.stockpile::UIGradient", 127, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(69, 89, 117)), ColorSequenceKeypoint.new(0.85, Color3.fromRGB(196, 206, 220)), ColorSequenceKeypoint.new(1, Color3.fromRGB(255, 255, 255))}),
	Rotation = 0,
})

rule(sheet, ".bar-count", 83, {
	TextColor3 = "$Metal",
	TextTransparency = 0,
	TextSize = 11,
	TextWrapped = false,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".lobby-panel", 84, {
	TextTransparency = 0.03,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.03,
	ImageTransparency = 0.03,
	GroupTransparency = 0.03,
	Size = UDim2.new(0, 360, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
	Position = UDim2.new(0.5, 0, 0, 80),
	AnchorPoint = Vector2.new(0.5, 0),
})

rule(sheet, ".lobby-panel::UIGradient", 84, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.03, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.04, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(0.55, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(1, Color3.fromRGB(1, 1, 2))}),
	Rotation = 90,
})

rule(sheet, ".lobby-panel::UIPadding", 84, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".lobby-panel::UIListLayout", 84, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	ItemLineAlignment = Enum.ItemLineAlignment.Stretch,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".lobby-title", 85, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 20,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".lobby-title::UIStroke", 85, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.15,
})

rule(sheet, ".lobby-panel.counting >> .lobby-title", 134, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
})

rule(sheet, ".lobby-hint", 86, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
})

rule(sheet, ".lobby-list::UIListLayout", 87, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".lobby-row", 88, {
	BackgroundColor3 = Color3.fromRGB(31, 40, 51),
	BackgroundTransparency = 0.2,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-row::UIPadding", 88, {
	PaddingTop = UDim.new(0, 4),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 4),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".lobby-row::UIStroke", 88, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".lobby-row::UIListLayout", 88, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".lobby-name", 89, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = false,
	TextTruncate = Enum.TextTruncate.AtEnd,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	ClipsDescendants = true,
})

rule(sheet, ".lobby-name.you", 129, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".lobby-status", 90, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Right,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".lobby-row.ready >> .lobby-status", 135, {
	TextColor3 = "$Gain",
	TextTransparency = 0,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

return sheet
