"""Upload the art's meshes to Roblox through Open Cloud, so the game can load them as assets.

Plain python3 (not Blender's bpy); needs `requests`. Build first (build.ps1): a build records each model in built.json
and writes build/<name>_art.glb, one node per mesh of it that is not on Roblox yet, named by the mesh's hash.

    python tools/model_pipeline/roblox/upload_art.py [name ...]

With no names it goes through every model in built.json, and skips those whose meshes are all on Roblox already. Each
other model's _art.glb is uploaded as one Model, of which Roblox makes a mesh asset per node. Which asset ids those are
only Studio can see, so the model is recorded in uploads.json as pending, with its asset id and the hashes it was
uploaded with; then `record_meshes.py script` writes the Luau that reads them in Studio, and `record_meshes.py record`
takes what it printed. The next build writes each uploaded mesh into its art module by asset id.

Nothing is uploaded twice: a model already uploaded with the meshes it is waiting for is waiting for `record` instead,
and one whose .glb no longer holds what it is waiting for (some of its meshes were recorded since it was built) has to be
rebuilt first, so that its .glb holds only what is still missing.

The key and the creator are tools/roblox_open_cloud.py's.
"""

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent.parent))

import manifest  # noqa: E402
import roblox_open_cloud  # noqa: E402


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("names", nargs="*", help="models to upload (default: every built one)")
    roblox_open_cloud.add_key_argument(parser)
    args = parser.parse_args()

    built = manifest.load_built()
    uploads = manifest.load_uploads()
    unknown = [name for name in args.names if name not in built]
    if unknown:
        sys.exit(f"never built: {', '.join(unknown)}")
    to_upload = []
    for name in args.names or sorted(built):
        entry = built[name]
        missing = manifest.pending_hashes(entry["hashes"], uploads)
        if not missing:
            continue
        model = uploads["models"].get(name)
        if model is not None and model["pending"] and sorted(model["hashes"]) == sorted(missing):
            print(f"{name}: uploaded already as model {model['asset_id']}, waiting for its meshes to be read "
                  "(record_meshes.py script)")
        elif sorted(entry["pending"]) != sorted(missing):
            print(f"{name}: its upload file is out of date, some of its meshes were recorded since; rebuild it first "
                  f"(build.ps1 {name})")
        elif not manifest.glb_path(name).is_file():
            print(f"{name}: no {manifest.glb_path(name)}; rebuild it first (build.ps1 {name})")
        else:
            to_upload.append((name, missing))
    if not to_upload:
        print("nothing to upload")
        return
    key = roblox_open_cloud.api_key(args.api_key)
    for name, missing in to_upload:
        asset_id = roblox_open_cloud.upload(
            manifest.glb_path(name),
            "Model",
            "model/gltf-binary",
            f"rts_{name}_art",
            f"Procedurally generated by tools/model_pipeline ({name})",
            key,
        )
        uploads["models"][name] = {"asset_id": asset_id, "hashes": missing, "pending": True}
        manifest.save_uploads(uploads)
        print(f"{name}: uploaded as model {asset_id}")
    print("next: python tools/model_pipeline/roblox/record_meshes.py script, and run what it writes in Studio")


if __name__ == "__main__":
    main()
