"""Upload a .glb as a Roblox Mesh/Model asset via the Open Cloud Assets API.

Plain python3 (not Blender's bpy) — only needs `requests`.

    python upload_open_cloud.py build/building_basic.glb --creator-type User --creator-id 123456

Reads the API key from $ROBLOX_API_KEY (or --api-key). Prints the numeric asset id once Roblox
finishes moderating the upload, so it can be fed to mcp__Roblox_Studio__insert_asset.

https://create.roblox.com/docs/cloud/reference/Asset
"""

import argparse
import json
import os
import sys
import time
from pathlib import Path

import requests

ASSETS_URL = "https://apis.roblox.com/assets/v1/assets"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("glb_path", type=Path)
    parser.add_argument("--creator-type", choices=["User", "Group"], required=True)
    parser.add_argument("--creator-id", required=True)
    parser.add_argument("--name", default=None, help="asset display name (default: filename stem)")
    parser.add_argument("--api-key", default=os.environ.get("ROBLOX_API_KEY"))
    parser.add_argument("--poll-seconds", type=float, default=3.0)
    parser.add_argument("--timeout-seconds", type=float, default=180.0)
    return parser.parse_args()


def main():
    args = parse_args()
    if not args.api_key:
        sys.exit("no API key: pass --api-key or set ROBLOX_API_KEY")
    if not args.glb_path.is_file():
        sys.exit(f"no such file: {args.glb_path}")

    request_payload = {
        "assetType": "Model",
        "displayName": args.name or args.glb_path.stem,
        "description": f"Procedurally generated by tools/model_pipeline ({args.glb_path.name})",
        "creationContext": {
            "creator": {
                ("userId" if args.creator_type == "User" else "groupId"): str(args.creator_id)
            }
        },
    }

    with args.glb_path.open("rb") as glb_file:
        response = requests.post(
            ASSETS_URL,
            headers={"x-api-key": args.api_key},
            data={"request": json.dumps(request_payload)},
            files={"fileContent": (args.glb_path.name, glb_file, "model/gltf-binary")},
        )
    response.raise_for_status()
    operation = response.json()
    operation_path = operation["path"]

    deadline = time.time() + args.timeout_seconds
    while time.time() < deadline:
        status_response = requests.get(
            f"https://apis.roblox.com/assets/v1/{operation_path}",
            headers={"x-api-key": args.api_key},
        )
        status_response.raise_for_status()
        status = status_response.json()
        if status.get("done"):
            if "error" in status:
                sys.exit(f"upload failed: {status['error']}")
            asset_id = status["response"]["assetId"]
            print(asset_id)
            return
        time.sleep(args.poll_seconds)

    sys.exit("timed out waiting for Roblox to finish processing the upload")


if __name__ == "__main__":
    main()
