"""Upload the art's meshes to Roblox through Open Cloud, so the client can load them as assets.

Plain python3 (not Blender's bpy); only needs `requests`. Run a build first: it writes each model's art module
(src/shared/art/<def>.luau) and, next to its .glb, build/<def>_art.glb, one node per mesh named by the mesh's hash.

    python tools/model_pipeline/roblox/upload_art.py --creator-type User --creator-id 123456 [def ...]

With no defs it goes through every art module. A def whose meshes are all uploaded already is skipped. Each
other def's _art.glb is uploaded as one Model; Roblox makes a mesh asset of every node in it. Which asset ids
those are is only visible from inside Studio (InsertService:LoadAsset), so the model's id is recorded in
roblox/uploads.json as pending, and roblox/record_meshes.py fills in its meshes once Studio has read them. The
next build then writes each uploaded mesh into the art module as its asset id.

The API key is read from roblox/.api_key or rbxopencloudkey.txt at the repo root (both gitignored), or
$ROBLOX_API_KEY, or --api-key. It needs asset:read and
asset:write for the creator.
"""

import argparse
import json
import os
import re
import sys
import time
from pathlib import Path

import requests

ROBLOX_DIR = Path(__file__).resolve().parent
PIPELINE_ROOT = ROBLOX_DIR.parent
ART_DIR = PIPELINE_ROOT.parent.parent / "src" / "shared" / "art"
BUILD_DIR = PIPELINE_ROOT / "build"
UPLOADS_PATH = ROBLOX_DIR / "uploads.json"
# where the key may be kept, first found wins; both are gitignored
KEY_PATHS = [ROBLOX_DIR / ".api_key", PIPELINE_ROOT.parent.parent / "rbxopencloudkey.txt"]
ASSETS_URL = "https://apis.roblox.com/assets/v1/assets"


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("defs", nargs="*", help="defs to upload (default: every art module)")
    parser.add_argument("--creator-type", choices=["User", "Group"], required=True)
    parser.add_argument("--creator-id", required=True)
    parser.add_argument("--api-key", default=None)
    parser.add_argument("--poll-seconds", type=float, default=3.0)
    parser.add_argument("--timeout-seconds", type=float, default=300.0)
    return parser.parse_args()


def api_key(args):
    if args.api_key:
        return args.api_key
    for path in KEY_PATHS:
        if path.is_file():
            return path.read_text(encoding="utf-8").strip()
    return os.environ.get("ROBLOX_API_KEY")


def load_uploads():
    if UPLOADS_PATH.is_file():
        return json.loads(UPLOADS_PATH.read_text(encoding="utf-8"))
    return {"meshes": {}, "models": {}}


def save_uploads(uploads):
    UPLOADS_PATH.write_text(json.dumps(uploads, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def hashes_of(def_name):
    source = (ART_DIR / f"{def_name}.luau").read_text(encoding="utf-8")
    return re.findall(r'hash = "([0-9a-f]+)"', source)


def upload(glb_path, def_name, args, key):
    request_payload = {
        "assetType": "Model",
        "displayName": f"rts_{def_name}_art",
        "description": f"Procedurally generated by tools/model_pipeline ({def_name})",
        "creationContext": {
            "creator": {("userId" if args.creator_type == "User" else "groupId"): str(args.creator_id)}
        },
    }
    with glb_path.open("rb") as glb_file:
        response = requests.post(
            ASSETS_URL,
            headers={"x-api-key": key},
            data={"request": json.dumps(request_payload)},
            files={"fileContent": (glb_path.name, glb_file, "model/gltf-binary")},
        )
    if response.status_code >= 400:
        sys.exit(f"{def_name}: upload refused ({response.status_code}): {response.text}")
    operation_path = response.json()["path"]

    deadline = time.time() + args.timeout_seconds
    while time.time() < deadline:
        status_response = requests.get(f"https://apis.roblox.com/assets/v1/{operation_path}", headers={"x-api-key": key})
        if status_response.status_code >= 400:
            sys.exit(f"{def_name}: could not read the upload's status ({status_response.status_code}): {status_response.text}")
        status = status_response.json()
        if status.get("done"):
            if "error" in status:
                sys.exit(f"{def_name}: upload failed: {status['error']}")
            return status["response"]["assetId"]
        time.sleep(args.poll_seconds)
    sys.exit(f"{def_name}: timed out waiting for Roblox to finish processing the upload")


def main():
    args = parse_args()
    key = api_key(args)
    if not key:
        sys.exit(f"no API key: put one in {KEY_PATHS[0]}, set ROBLOX_API_KEY, or pass --api-key")

    defs = args.defs or sorted(p.stem for p in ART_DIR.glob("*.luau") if p.stem != "init")
    uploads = load_uploads()
    for def_name in defs:
        hashes = hashes_of(def_name)
        if all(h in uploads["meshes"] for h in hashes):
            print(f"{def_name}: already uploaded")
            continue
        glb_path = BUILD_DIR / f"{def_name}_art.glb"
        if not glb_path.is_file():
            sys.exit(f"{def_name}: no {glb_path}; build it first")
        asset_id = upload(glb_path, def_name, args, key)
        uploads["models"][def_name] = {"asset_id": str(asset_id), "hashes": hashes, "pending": True}
        save_uploads(uploads)
        print(f"{def_name}: uploaded as model {asset_id}")


if __name__ == "__main__":
    main()
