"""The art module format, in one place: what build.py writes into src/shared/art/<name>.luau (and ui_art/,
reclaimable_art/), and what src/shared/art/init.luau's `Group` and `Part` types say it holds. Plain Python: build.py
writes modules with `module_text`, and check_art.py holds the Luau types to GROUP_FIELDS and PART_FIELDS with
`type_problems`, so the writer and the types cannot drift apart.

A module is `groups`, the model's rigid pieces by name, and `parts`, one mesh per material of a piece. Every field is
(name, kind, required), written in this order, an optional one only when it has a value:

- "point": three numbers, Roblox's axes ({ x, y, z })
- "rgb": a colour's three 0-1 channels ({ r, g, b })
- "number", "integer", "text"
- "flag": written `= true` when set, left out otherwise
- "asset": a Roblox asset id, written as its rbxassetid:// content
"""

import re

# How a piece moves, its group's `kind` (common.art_group describes each).
GROUP_KINDS = ("turret", "work", "spin", "leg", "wheel", "hatch")

GROUP_FIELDS = (
    ("pivot", "point", True),
    ("kind", "text", False),
    ("weapon", "integer", False),
    ("axis", "point", False),
    ("speed", "number", False),
    ("swing", "number", False),
    ("phase", "number", False),
    ("stride", "number", False),
    ("radius", "number", False),
    ("open", "number", False),
)

PART_FIELDS = (
    ("group", "text", True),
    ("color", "rgb", True),
    ("offset", "point", True),
    ("size", "point", True),
    ("hash", "text", True),
    ("neon", "flag", False),
    ("team", "flag", False),
    ("mesh", "asset", False),
)

# The group fields a generator sets on a piece's objects (common.art_group), as `art_<name>`: all but its pivot,
# which is the location of the piece's object marked `art_pivot`.
META_FIELDS = tuple(field for field in GROUP_FIELDS if field[0] != "pivot")

# The Luau type each kind is declared as in src/shared/art/init.luau (a group's kind is its own union, GroupKind).
LUAU_TYPES = {
    "point": "{ number }",
    "rgb": "{ number }",
    "number": "number",
    "integer": "number",
    "text": "string",
    "flag": "boolean",
    "asset": "string",
}


def lua_number(value):
    """A number as the modules write it: four decimals at most, no trailing zeros, and never "-0"."""
    text = f"{value:.4f}".rstrip("0").rstrip(".")
    return "0" if text in ("-0", "") else text


def _value(kind, value):
    if kind in ("point", "rgb"):
        return "{ " + ", ".join(lua_number(c) for c in value[:3]) + " }"
    if kind == "number":
        return lua_number(value)
    if kind == "integer":
        return str(int(value))
    if kind == "text":
        return f'"{value}"'
    if kind == "flag":
        return "true"
    if kind == "asset":
        return f'"rbxassetid://{value}"'
    raise ValueError(f"no such kind {kind}")


def _fields(spec, record):
    """`record`'s fields as Luau, in the order `spec` lists them; a missing, None or false optional field is left out."""
    out = []
    for name, kind, required in spec:
        value = record.get(name)
        if value is None or (kind == "flag" and not value):
            if required:
                raise ValueError(f"art field {name} is required")
            continue
        out.append(f"{name} = {_value(kind, value)}")
    unknown = set(record) - {name for name, _, _ in spec}
    if unknown:
        raise ValueError(f"not in the art format: {', '.join(sorted(unknown))}")
    return ", ".join(out)


def module_text(generator, groups, parts):
    """The art module of `generator`: `groups` maps each piece's name to its fields, `parts` lists each mesh's."""
    lines = [
        f"-- Generated by tools/model_pipeline from generators/{generator}.py. Do not edit: rebuild it instead.",
        "return {",
        "\tgroups = {",
    ]
    for name, group in groups.items():
        kind = group.get("kind")
        if kind is not None and kind not in GROUP_KINDS:
            raise ValueError(f"{generator}: group {name} has kind {kind}, not one of {', '.join(GROUP_KINDS)}")
        lines.append(f"\t\t{name} = {{ {_fields(GROUP_FIELDS, group)} }},")
    lines.append("\t},")
    lines.append("\tparts = {")
    for part in parts:
        lines.append(f"\t\t{{ {_fields(PART_FIELDS, part)} }},")
    lines.append("\t},")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def module_hashes(text):
    """The mesh hashes an art module's parts name, in order, and how many of them name no uploaded mesh."""
    hashes = re.findall(r'\bhash = "(\w+)"', text)
    unnamed = sum(1 for line in text.splitlines() if "hash = " in line and "mesh = " not in line)
    return hashes, unnamed


def _luau_type(text, type_name):
    """The fields of `export type <type_name> = { ... }` in Luau source: {name: (type, optional)}."""
    match = re.search(rf"export type {type_name} = \{{\n(.*?)\n\}}", text, re.S)
    if match is None:
        return None
    fields = {}
    for line in match.group(1).splitlines():
        field = re.match(r"\s*(\w+): (.+?),\s*$", line)
        if field is not None:
            declared = field.group(2)
            fields[field.group(1)] = (declared.rstrip("?"), declared.endswith("?"))
    return fields


def type_problems(types_text):
    """How the Luau types (src/shared/art/init.luau's source) disagree with GROUP_FIELDS, PART_FIELDS and
    GROUP_KINDS."""
    problems = []
    kinds = re.search(r"export type GroupKind = (.+)", types_text)
    declared_kinds = tuple(re.findall(r'"(\w+)"', kinds.group(1))) if kinds is not None else ()
    if declared_kinds != GROUP_KINDS:
        problems.append(f"GroupKind is {' | '.join(declared_kinds) or 'missing'}, the writer's {', '.join(GROUP_KINDS)}")
    for type_name, spec in (("Group", GROUP_FIELDS), ("Part", PART_FIELDS)):
        declared = _luau_type(types_text, type_name)
        if declared is None:
            problems.append(f"no `export type {type_name}`")
            continue
        for name, kind, required in spec:
            want = "GroupKind" if (type_name, name) == ("Group", "kind") else LUAU_TYPES[kind]
            if name not in declared:
                problems.append(f"{type_name}.{name} is written but not declared")
            elif declared[name] != (want, not required):
                luau, optional = declared[name]
                problems.append(f"{type_name}.{name} is declared {luau}{'?' if optional else ''}, written as {want}{'' if required else '?'}")
        for name in declared:
            if name not in {field[0] for field in spec}:
                problems.append(f"{type_name}.{name} is declared but never written")
    return problems
