"""Where the defs' turret weapons fire from: each generator's MOUNTS, written into
src/shared/unit_defs/turret_mounts.luau, which the simulation reads (shared/unit_defs gives each mount to its weapon as
`turret`, and server/muzzles.luau fires the weapon from it). Plain Python: build.py writes the module after a build,
and check_art.py fails if it is not what the generators declare.

A generator whose model has a turret piece (common.art_group kind="turret") declares, for the weapon it fires, where
the turret turns (`pivot`, from the model's origin: the ground under the middle of its collider) and where its shots
leave it (`muzzle`, from the pivot, with the turret at rest facing ahead), in studs and Roblox's axes:

    MOUNTS = {1: {"pivot": (0, 1.3, 0), "muzzle": (0, 0.2, 1.1)}}

The art only has to agree (build.py's mount_problems): the pivot of the piece, and the point of it that reaches furthest
forward, the tip of its barrel. So regenerating a model never moves where it fires from; a change that moves a turret or
the tip of its barrel by more than TOLERANCE fails the build until its MOUNTS says so too.
"""

import art_format
import manifest

PATH = manifest.REPO_ROOT / "src" / "shared" / "unit_defs" / "turret_mounts.luau"

# How far a turret's art may be from its declared mount, in studs, on any axis.
TOLERANCE = 0.01


def module_text(declared):
    """The module, from `declared` (each generator's declarations, by name): every def's mounts, by weapon."""
    lines = [
        "--!strict",
        "-- Generated by tools/model_pipeline from each generator's MOUNTS (tools/model_pipeline/turret_mounts.py). Do not",
        "-- edit: change the generator's MOUNTS and rebuild it.",
        "--",
        "-- Where each def's turret weapons fire from, by def and weapon (types.TurretMount): shared/unit_defs gives each to",
        "-- its weapon as `turret`. The art is only checked to agree, so regenerating a model never moves where it fires from.",
        "",
        'local ReplicatedStorage = game:GetService "ReplicatedStorage"',
        "",
        "local types = require(ReplicatedStorage.Shared.types)",
        "",
        "type TurretMount = types.TurretMount",
        "",
        "local mounts: { [string]: { [number]: TurretMount } } = {",
    ]
    by_def = {}
    for name, declarations in declared.items():
        if "MOUNTS" in declarations:
            if "DEF" not in declarations:
                raise SystemExit(f"generators/{name}.py declares MOUNTS but no DEF to give them to")
            by_def[declarations["DEF"]] = declarations["MOUNTS"]
    for def_name in sorted(by_def):
        lines.append(f"\t{def_name} = {{")
        for weapon, mount in sorted(by_def[def_name].items()):
            pivot, muzzle = (", ".join(art_format.lua_number(c) for c in mount[key]) for key in ("pivot", "muzzle"))
            lines.append(f"\t\t[{weapon}] = {{ pivot = Vector3.new({pivot}), muzzle = Vector3.new({muzzle}) }},")
        lines.append("\t},")
    lines += ["}", "", "return table.freeze(mounts)", ""]
    return "\n".join(lines)


def write(declared):
    PATH.write_text(module_text(declared), encoding="utf-8", newline="\n")


def problems(declared):
    """What is wrong with the committed module: that it is not what the generators declare."""
    if not PATH.is_file() or PATH.read_text(encoding="utf-8") != module_text(declared):
        return [f"{PATH.relative_to(manifest.REPO_ROOT).as_posix()}: is not what the generators' MOUNTS say; rebuild (build.ps1 -Stale)"]
    return []
