-- Generated by outlass 0.1.0 from src/lobby/client/stylesheets/lobby.scss. Do not edit by hand.

local sheet = Instance.new("StyleSheet")
sheet.Name = "lobby"
sheet:SetAttribute("Void", Color3.fromRGB(8, 11, 15))
sheet:SetAttribute("Steel", Color3.fromRGB(20, 26, 34))
sheet:SetAttribute("SteelRaised", Color3.fromRGB(31, 40, 51))
sheet:SetAttribute("SteelLit", Color3.fromRGB(52, 66, 82))
sheet:SetAttribute("Edge", Color3.fromRGB(78, 96, 118))
sheet:SetAttribute("Text", Color3.fromRGB(236, 244, 252))
sheet:SetAttribute("TextDim", Color3.fromRGB(186, 202, 220))
sheet:SetAttribute("TextFaint", Color3.fromRGB(146, 166, 188))
sheet:SetAttribute("Metal", Color3.fromRGB(196, 206, 220))
sheet:SetAttribute("Energy", Color3.fromRGB(255, 230, 64))
sheet:SetAttribute("Buildpower", Color3.fromRGB(126, 240, 154))
sheet:SetAttribute("Gain", Color3.fromRGB(96, 224, 128))
sheet:SetAttribute("Danger", Color3.fromRGB(238, 88, 74))
sheet:SetAttribute("Caution", Color3.fromRGB(236, 184, 68))
sheet:SetAttribute("Accent", Color3.fromRGB(96, 210, 242))
sheet:SetAttribute("Resurrect", Color3.fromRGB(176, 96, 240))
sheet:SetAttribute("Fight", Color3.fromRGB(255, 138, 64))

local function rule(parent: Instance, selector: string, priority: number?, properties: { [string]: any }?): StyleRule
	local r = Instance.new("StyleRule")
	r.Name = selector
	r.Selector = selector
	if priority then
		r.Priority = priority
	end
	if properties then
		r:SetProperties(properties)
	end
	r.Parent = parent
	return r
end

rule(sheet, "TextLabel, TextButton, TextBox", 0, {
	RichText = true,
	TextWrapped = true,
})

rule(sheet, "ScrollingFrame", 0, {
	AutomaticCanvasSize = Enum.AutomaticSize.XY,
	CanvasSize = UDim2.new(),
})

rule(sheet, "Frame, TextLabel, TextButton, TextBox, ImageLabel, ImageButton, ScrollingFrame, CanvasGroup, VideoFrame, ViewportFrame", 0, {
	AutomaticSize = Enum.AutomaticSize.XY,
})

rule(sheet, "Frame, TextButton, TextLabel", 1, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
})

rule(sheet, "Frame::UIStroke, TextButton::UIStroke, TextLabel::UIStroke", 1, {
	Enabled = false,
})

rule(sheet, "TextLabel, TextButton", 2, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Center,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".panel", 5, {
	TextTransparency = 0.03,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.03,
	ImageTransparency = 0.03,
	GroupTransparency = 0.03,
})

rule(sheet, ".panel::UIGradient", 5, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.03, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.04, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(0.55, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(1, Color3.fromRGB(1, 1, 2))}),
	Rotation = 90,
})

rule(sheet, ".panel::UIPadding", 5, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".rail", 6, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 2),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".rail::UIGradient", 6, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(0.55, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(0.55, 0), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 0,
})

rule(sheet, ".hazard", 7, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".hazard::UIGradient", 7, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.12, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.12, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.25, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.25, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.37, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.37, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.5, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.5, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.62, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.62, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.75, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.75, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.87, Color3.fromRGB(238, 88, 74)), ColorSequenceKeypoint.new(0.87, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(1, Color3.fromRGB(8, 11, 15))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.1), NumberSequenceKeypoint.new(0.12, 0.1), NumberSequenceKeypoint.new(0.25, 0.1), NumberSequenceKeypoint.new(0.37, 0.1), NumberSequenceKeypoint.new(0.5, 0.1), NumberSequenceKeypoint.new(0.62, 0.1), NumberSequenceKeypoint.new(0.75, 0.1), NumberSequenceKeypoint.new(0.87, 0.1), NumberSequenceKeypoint.new(1, 0.1)}),
	Rotation = -45,
})

rule(sheet, ".faint", 8, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
})

rule(sheet, ".metal", 9, {
	TextColor3 = "$Metal",
	TextTransparency = 0,
})

rule(sheet, ".energy", 10, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
})

rule(sheet, ".accent", 11, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
})

rule(sheet, ".heading", 12, {
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".heading::UIStroke", 12, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.15,
})

rule(sheet, ".readout", 13, {
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".readout::UIStroke", 13, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.2,
})

rule(sheet, ".grow::UIFlexItem", 14, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, "ScrollingFrame", 3, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
	ClipsDescendants = true,
	ScrollingEnabled = true,
	ScrollingDirection = Enum.ScrollingDirection.Y,
	AutomaticCanvasSize = Enum.AutomaticSize.Y,
	CanvasSize = UDim2.new(),
	ScrollBarThickness = 8,
	ScrollBarImageColor3 = Color3.fromRGB(78, 96, 118),
	ScrollBarImageTransparency = 0,
})

rule(sheet, "ScrollingFrame::UIStroke", 3, {
	Enabled = false,
})

rule(sheet, "ImageLabel", 4, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
})

rule(sheet, "ImageLabel::UIStroke", 4, {
	Enabled = false,
})

rule(sheet, ".accent-bar", 15, {
	BackgroundColor3 = "$Accent",
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 4, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".accent-bar.tall", 132, {
	Size = UDim2.new(0, 4, 0, 34),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".title-row", 16, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".title-row::UIListLayout", 16, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".badge", 17, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.X,
	BorderSizePixel = 0,
})

rule(sheet, ".badge::UIPadding", 17, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".badge::UIStroke", 17, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".tag", 18, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 16),
	AutomaticSize = Enum.AutomaticSize.X,
	BorderSizePixel = 0,
})

rule(sheet, ".tag::UIPadding", 18, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 4),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".tag::UIStroke", 18, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".tag.friends, .tag.you", 133, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.friends::UIStroke, .tag.you::UIStroke", 133, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".tag.host", 134, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.host::UIStroke", 134, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".tag.ready", 135, {
	TextColor3 = "$Gain",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.ready::UIStroke", 135, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".seam", 19, {
	TextTransparency = 0.55,
	BackgroundColor3 = Color3.fromRGB(78, 96, 118),
	BackgroundTransparency = 0.55,
	ImageTransparency = 0.55,
	GroupTransparency = 0.55,
	Size = UDim2.new(1, 0, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
})

do
	local r1 = rule(sheet, ".button", 20, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 0, 0, 36),
		AutomaticSize = Enum.AutomaticSize.X,
		BorderSizePixel = 0,
		ClipsDescendants = true,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".button::UIGradient", 20, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".button::UIStroke", 20, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".button:Hover", 136, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button:Hover::UIStroke", 136, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".button:Press", 137, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".button:NonInteractable", 138, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".button:NonInteractable::UIStroke", 138, {
	Transparency = 0.6,
})

rule(sheet, ".button:Hover, .button.selected", 139, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button:Hover::UIGradient, .button.selected::UIGradient", 139, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(76, 89, 103)), ColorSequenceKeypoint.new(1, Color3.fromRGB(43, 54, 67))}),
	Rotation = 90,
})

rule(sheet, ".button:Hover::UIStroke, .button.selected::UIStroke", 139, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".button:Hover >> .button-label, .button.selected >> .button-label", 194, {
	TextColor3 = Color3.fromRGB(96, 210, 242),
	TextTransparency = 0,
})

rule(sheet, ".button:Hover >> .button-rail, .button.selected >> .button-rail", 195, {
	Size = UDim2.new(1, 0, 0, 2),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".button:Press", 140, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button:Press::UIGradient", 140, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(18, 23, 31)), ColorSequenceKeypoint.new(1, Color3.fromRGB(29, 35, 43))}),
	Rotation = 90,
})

rule(sheet, ".button:Press::UIStroke", 140, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".button.primary", 141, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button.primary::UIGradient", 141, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(60, 183, 217)), ColorSequenceKeypoint.new(1, Color3.fromRGB(13, 125, 157))}),
	Rotation = 90,
})

rule(sheet, ".button.primary::UIStroke", 141, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".button.primary:Hover, .button.primary.selected", 196, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button.primary:Hover::UIGradient, .button.primary.selected::UIGradient", 196, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(111, 214, 243)), ColorSequenceKeypoint.new(1, Color3.fromRGB(39, 157, 191))}),
	Rotation = 90,
})

rule(sheet, ".button.primary:Hover::UIStroke, .button.primary.selected::UIStroke", 196, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(181, 234, 249),
	Transparency = 0,
})

rule(sheet, ".button.primary:Hover >> .button-label, .button.primary.selected >> .button-label", 222, {
	TextColor3 = Color3.fromRGB(255, 255, 255),
	TextTransparency = 0,
})

rule(sheet, ".button.primary:Hover >> .button-rail, .button.primary.selected >> .button-rail", 223, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".button.primary:Press", 197, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".button.primary:Press::UIGradient", 197, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(12, 116, 145)), ColorSequenceKeypoint.new(1, Color3.fromRGB(38, 148, 179))}),
	Rotation = 90,
})

rule(sheet, ".button.locked, .button:NonInteractable", 142, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".button.locked::UIStroke, .button:NonInteractable::UIStroke", 142, {
	Transparency = 0.6,
})

rule(sheet, ".button.join", 143, {
	Size = UDim2.new(0, 96, 0, 36),
	AutomaticSize = Enum.AutomaticSize.None,
})

do
	local r1 = rule(sheet, ".button-label", 21, {
		TextSize = 12,
		FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
		Size = UDim2.new(0, 0, 1, 0),
		AutomaticSize = Enum.AutomaticSize.X,
	})
	r1:SetPropertyTransitions({
		TextColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".button-label::UIPadding", 21, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 20),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 20),
})

rule(sheet, ".button.join > .button-label, .button.play > .button-label", 198, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

do
	local r1 = rule(sheet, ".button-rail", 22, {
		BackgroundColor3 = Color3.fromRGB(96, 210, 242),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 0, 0, 2),
		AutomaticSize = Enum.AutomaticSize.None,
		Position = UDim2.new(0.5, 0, 1, 0),
		AnchorPoint = Vector2.new(0.5, 1),
		ZIndex = 2,
		Interactable = false,
	})
	r1:SetPropertyTransitions({
		Size = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".button-sheen", 23, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
	ZIndex = 3,
	Interactable = false,
})

do
	local r1 = rule(sheet, ".chip", 24, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 0, 0, 30),
		AutomaticSize = Enum.AutomaticSize.X,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".chip::UIGradient", 24, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".chip::UIPadding", 24, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".chip::UIStroke", 24, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".chip::UIListLayout", 24, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".chip:Hover", 144, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip:Hover::UIStroke", 144, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".chip:Press", 145, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".chip:NonInteractable", 146, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".chip:NonInteractable::UIStroke", 146, {
	Transparency = 0.6,
})

rule(sheet, ".chip.active", 147, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.active::UIGradient", 147, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(43, 151, 181)), ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 109, 137))}),
	Rotation = 90,
})

rule(sheet, ".chip.active::UIStroke", 147, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".chip:Hover", 148, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip:Hover::UIGradient", 148, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(76, 89, 103)), ColorSequenceKeypoint.new(1, Color3.fromRGB(43, 54, 67))}),
	Rotation = 90,
})

rule(sheet, ".chip:Hover::UIStroke", 148, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".chip:Hover > .chip-label", 199, {
	TextColor3 = "$Text",
	TextTransparency = 0,
})

rule(sheet, ".chip.active:Hover", 200, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.active:Hover::UIGradient", 200, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(70, 192, 226)), ColorSequenceKeypoint.new(1, Color3.fromRGB(15, 143, 179))}),
	Rotation = 90,
})

rule(sheet, ".chip.active:Hover::UIStroke", 200, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(181, 234, 249),
	Transparency = 0,
})

rule(sheet, ".chip:Press", 149, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip:Press::UIGradient", 149, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(18, 23, 31)), ColorSequenceKeypoint.new(1, Color3.fromRGB(29, 35, 43))}),
	Rotation = 90,
})

rule(sheet, ".chip:Press::UIStroke", 149, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".chip.locked:Hover", 201, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.locked:Hover::UIStroke", 201, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".chip.locked.active:Hover", 224, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.locked.active:Hover::UIGradient", 224, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(43, 151, 181)), ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 109, 137))}),
	Rotation = 90,
})

rule(sheet, ".chip.locked.active:Hover::UIStroke", 224, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

do
	local r1 = rule(sheet, ".chip-label", 25, {
		TextColor3 = "$TextDim",
		TextTransparency = 0,
		TextSize = 13,
		FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	})
	r1:SetPropertyTransitions({
		TextColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".chip.active > .chip-label", 202, {
	TextColor3 = "$Text",
	TextTransparency = 0,
})

rule(sheet, ".backdrop", 26, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
	Interactable = false,
})

rule(sheet, ".backdrop::UIGradient", 26, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.45, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(0.72, Color3.fromRGB(8, 11, 15)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.12), NumberSequenceKeypoint.new(0.45, 0.3), NumberSequenceKeypoint.new(0.72, 0.9), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 0,
})

rule(sheet, ".backdrop.room-view", 150, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.45,
})

rule(sheet, ".vignette", 27, {
	BackgroundTransparency = 1,
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
})

rule(sheet, ".backdrop-rail", 28, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 2),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
})

rule(sheet, ".backdrop-rail::UIGradient", 28, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 0)), ColorSequenceKeypoint.new(0.3, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(0.7, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.3, 0), NumberSequenceKeypoint.new(0.7, 0), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 0,
})

rule(sheet, ".shell", 29, {
	Size = UDim2.new(0, 1240, 0, 720),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0.5, 0, 0.5, 0),
	AnchorPoint = Vector2.new(0.5, 0.5),
})

rule(sheet, ".shell::UIListLayout", 29, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".shell.browsing > .body > .browser", 225, {
	Size = UDim2.new(0, 800, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header", 30, {
	Size = UDim2.new(1, 0, 0, 72),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header::UIPadding", 30, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 4),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".header::UIListLayout", 30, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 16),
})

rule(sheet, ".header-titles", 31, {
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".header-titles::UIListLayout", 31, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".header-title", 32, {
	TextSize = 34,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 40),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header-title::UIStroke", 32, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 3,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.1,
})

rule(sheet, ".header-subtitle", 33, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header-subtitle::UIStroke", 33, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.2,
})

rule(sheet, ".panel", 34, {
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	ImageTransparency = 0,
	GroupTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".panel::UIGradient", 34, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(52, 66, 82)), ColorSequenceKeypoint.new(0.06, Color3.fromRGB(20, 26, 34)), ColorSequenceKeypoint.new(1, Color3.fromRGB(8, 11, 15))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.25), NumberSequenceKeypoint.new(0.06, 0.38), NumberSequenceKeypoint.new(1, 0.22)}),
	Rotation = 90,
})

rule(sheet, ".panel::UIStroke", 34, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0.4,
})

rule(sheet, ".body", 35, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".body::UIFlexItem", 35, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".notice", 36, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.08,
	TextSize = 13,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	AutomaticSize = Enum.AutomaticSize.XY,
	Position = UDim2.new(0.5, 0, 1, -32),
	AnchorPoint = Vector2.new(0.5, 1),
	ZIndex = 10,
	BorderSizePixel = 0,
})

rule(sheet, ".notice::UIPadding", 36, {
	PaddingTop = UDim.new(0, 8),
	PaddingRight = UDim.new(0, 20),
	PaddingBottom = UDim.new(0, 8),
	PaddingLeft = UDim.new(0, 20),
})

rule(sheet, ".notice::UIStroke", 36, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".browser", 37, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".browser::UIListLayout", 37, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".lobby-columns", 38, {
	Size = UDim2.new(1, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-columns::UIPadding", 38, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".lobby-columns::UIListLayout", 38, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".column-name", 39, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".join-space", 40, {
	Size = UDim2.new(0, 96, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-list", 41, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-list::UIListLayout", 41, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".lobby-list::UIFlexItem", 41, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".lobby-row", 42, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 60),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-row::UIGradient", 42, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(48, 56, 66)), ColorSequenceKeypoint.new(1, Color3.fromRGB(24, 30, 39))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.188), NumberSequenceKeypoint.new(1, 0.16)}),
	Rotation = 0,
})

rule(sheet, ".lobby-row::UIPadding", 42, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

do
	local r1 = rule(sheet, ".lobby-row::UIStroke", 42, {
		Enabled = true,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		Thickness = 1,
		Color = Color3.fromRGB(78, 96, 118),
		Transparency = 0.3,
	})
	r1:SetPropertyTransitions({
		Color = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		Transparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".lobby-row::UIListLayout", 42, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".lobby-row:Hover", 151, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-row:Hover::UIGradient", 151, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(59, 89, 108)), ColorSequenceKeypoint.new(1, Color3.fromRGB(43, 55, 68))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.129), NumberSequenceKeypoint.new(1, 0.1275)}),
	Rotation = 0,
})

rule(sheet, ".lobby-row:Hover::UIStroke", 151, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".lobby-row:Hover >> .lobby-host", 203, {
	TextColor3 = Color3.fromRGB(96, 210, 242),
	TextTransparency = 0,
})

rule(sheet, ".lobby-thumb", 43, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 76, 0, 48),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-thumb::UIStroke", 43, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(37, 46, 57),
	Transparency = 0,
})

rule(sheet, ".lobby-thumb.blank", 152, {
	BackgroundTransparency = 1,
	Size = UDim2.new(0, 76, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-thumb.blank::UIStroke", 152, {
	Enabled = false,
})

rule(sheet, ".lobby-cell", 44, {
	TextXAlignment = Enum.TextXAlignment.Left,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.host::UIListLayout", 153, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".lobby-cell.host::UIFlexItem", 153, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".lobby-cell.mode", 154, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	Size = UDim2.new(0, 110, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.map", 155, {
	Size = UDim2.new(0, 190, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.map::UIListLayout", 155, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".lobby-cell.players", 156, {
	TextXAlignment = Enum.TextXAlignment.Right,
	Size = UDim2.new(0, 80, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.players.full", 204, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
})

rule(sheet, ".lobby-cell.column-name", 157, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
})

do
	local r1 = rule(sheet, ".lobby-host", 45, {
		TextSize = 15,
		TextXAlignment = Enum.TextXAlignment.Left,
		FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
		Size = UDim2.new(1, 0, 0, 20),
		AutomaticSize = Enum.AutomaticSize.None,
	})
	r1:SetPropertyTransitions({
		TextColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".lobby-map-name, .lobby-map-size", 46, {
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(1, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-map-size", 47, {
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".empty", 48, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.6,
	TextSize = 14,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 160),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".empty::UIStroke", 48, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0.2,
})

rule(sheet, ".room", 49, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".room::UIListLayout", 49, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".room-side", 50, {
	Size = UDim2.new(0, 524, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".room-side::UIListLayout", 50, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".map-panel", 51, {
	Size = UDim2.new(0, 704, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-panel::UIListLayout", 51, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".map-stage", 52, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 300),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".map-stage::UIGradient", 52, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(15, 20, 26)), ColorSequenceKeypoint.new(1, Color3.fromRGB(8, 11, 15))}),
	Rotation = 90,
})

rule(sheet, ".map-stage::UIStroke", 52, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(37, 46, 57),
	Transparency = 0,
})

rule(sheet, ".map-fit", 53, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0.5, 0, 0.5, 0),
	AnchorPoint = Vector2.new(0.5, 0.5),
	BorderSizePixel = 0,
})

rule(sheet, ".map-fit::UIStroke", 53, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".map-picture", 54, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 1,
})

rule(sheet, ".map-drawing", 55, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 2,
})

rule(sheet, ".map-grid", 56, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 3,
	Interactable = false,
})

rule(sheet, ".grid-line", 57, {
	TextTransparency = 0.78,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.78,
	ImageTransparency = 0.78,
	GroupTransparency = 0.78,
})

rule(sheet, ".grid-line.column", 158, {
	Size = UDim2.new(0, 1, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".grid-line.row", 159, {
	Size = UDim2.new(1, 0, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".facts", 58, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".facts::UIListLayout", 58, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 20),
})

rule(sheet, ".fact", 59, {
	Size = UDim2.new(0, 84, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".fact::UIListLayout", 59, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".fact-label", 60, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".fact-value", 61, {
	TextSize = 17,
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(1, 0, 0, 22),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-description", 62, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Left,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".map-grid-note", 63, {
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
	Size = UDim2.new(1, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-list", 64, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-list::UIPadding", 64, {
	PaddingTop = UDim.new(0, 1),
	PaddingRight = UDim.new(0, 1),
	PaddingBottom = UDim.new(0, 1),
	PaddingLeft = UDim.new(0, 1),
})

rule(sheet, ".map-list::UIGridLayout", 64, {
	SortOrder = Enum.SortOrder.LayoutOrder,
	CellPadding = UDim2.new(0, 8, 0, 8),
	FillDirectionMaxCells = 4,
	CellSize = UDim2.new(0, 158, 0, 118),
})

rule(sheet, ".map-list::UIFlexItem", 64, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

do
	local r1 = rule(sheet, ".map-card", 65, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 158, 0, 118),
		AutomaticSize = Enum.AutomaticSize.None,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".map-card::UIGradient", 65, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".map-card::UIPadding", 65, {
	PaddingTop = UDim.new(0, 6),
	PaddingRight = UDim.new(0, 6),
	PaddingBottom = UDim.new(0, 6),
	PaddingLeft = UDim.new(0, 6),
})

rule(sheet, ".map-card::UIStroke", 65, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".map-card::UIListLayout", 65, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".map-card:Hover", 160, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card:Hover::UIStroke", 160, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".map-card:Press", 161, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".map-card:NonInteractable", 162, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".map-card:NonInteractable::UIStroke", 162, {
	Transparency = 0.6,
})

rule(sheet, ".map-card:Hover", 163, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card:Hover::UIGradient", 163, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(76, 89, 103)), ColorSequenceKeypoint.new(1, Color3.fromRGB(43, 54, 67))}),
	Rotation = 90,
})

rule(sheet, ".map-card:Hover::UIStroke", 163, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".map-card:Hover >> .map-card-name", 205, {
	TextColor3 = Color3.fromRGB(96, 210, 242),
	TextTransparency = 0,
})

rule(sheet, ".map-card.active", 164, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.active::UIGradient", 164, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(40, 124, 148)), ColorSequenceKeypoint.new(1, Color3.fromRGB(9, 85, 107))}),
	Rotation = 90,
})

rule(sheet, ".map-card.active::UIStroke", 164, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 2,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".map-card.active:Hover", 206, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.active:Hover::UIGradient", 206, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(57, 152, 178)), ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 106, 133))}),
	Rotation = 90,
})

rule(sheet, ".map-card.active:Hover::UIStroke", 206, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 2,
	Color = Color3.fromRGB(181, 234, 249),
	Transparency = 0,
})

rule(sheet, ".map-card.locked:Hover", 207, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.locked:Hover::UIGradient", 207, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".map-card.locked:Hover::UIStroke", 207, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".map-card.locked:Hover >> .map-card-name", 226, {
	TextColor3 = "$Text",
	TextTransparency = 0,
})

rule(sheet, ".map-card.locked.active:Hover", 227, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.locked.active:Hover::UIGradient", 227, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(40, 124, 148)), ColorSequenceKeypoint.new(1, Color3.fromRGB(9, 85, 107))}),
	Rotation = 90,
})

rule(sheet, ".map-card.locked.active:Hover::UIStroke", 227, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 2,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".map-card-thumb", 66, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 70),
	AutomaticSize = Enum.AutomaticSize.None,
})

do
	local r1 = rule(sheet, ".map-card-name", 67, {
		TextSize = 13,
		TextTruncate = Enum.TextTruncate.AtEnd,
		FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
		Size = UDim2.new(1, 0, 0, 16),
		AutomaticSize = Enum.AutomaticSize.None,
	})
	r1:SetPropertyTransitions({
		TextColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".map-card-size", 68, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 10,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 13),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-card-size.crowded", 165, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
})

rule(sheet, ".settings-panel", 69, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".settings-panel::UIListLayout", 69, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".group", 70, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".group::UIListLayout", 70, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".group-label", 71, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".chips", 72, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".chips::UIListLayout", 72, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
	Wraps = true,
})

rule(sheet, ".seats-panel", 73, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".seats-panel::UIListLayout", 73, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".seats-panel::UIFlexItem", 73, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".sides", 74, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".sides::UIPadding", 74, {
	PaddingRight = UDim.new(0, 12),
})

rule(sheet, ".sides::UIListLayout", 74, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 16),
})

rule(sheet, ".sides::UIFlexItem", 74, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".teams", 75, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".teams::UIListLayout", 75, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".teams.split::UIListLayout", 166, {
	FillDirection = Enum.FillDirection.Horizontal,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".side", 76, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".side::UIListLayout", 76, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".teams.split > .side", 208, {
	Size = UDim2.new(0, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".teams.split > .side::UIFlexItem", 208, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
	ShrinkRatio = 1,
})

rule(sheet, ".side-head", 77, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".side-head::UIListLayout", 77, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".side-head > .group-label", 167, {
	TextTruncate = Enum.TextTruncate.AtEnd,
	Size = UDim2.new(0, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".side-head > .group-label::UIFlexItem", 167, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
	ShrinkRatio = 1,
})

rule(sheet, ".side-count", 78, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.X,
})

rule(sheet, ".seat", 79, {
	BackgroundColor3 = Color3.fromRGB(31, 40, 51),
	BackgroundTransparency = 0.15,
	Size = UDim2.new(1, 0, 0, 30),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".seat::UIPadding", 79, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".seat::UIStroke", 79, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(48, 59, 72),
	Transparency = 0,
})

rule(sheet, ".seat::UIListLayout", 79, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".seat.you", 168, {
	BorderSizePixel = 0,
})

rule(sheet, ".seat.you::UIStroke", 168, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".seat.open", 169, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.5,
	TextSize = 12,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
	BorderSizePixel = 0,
})

rule(sheet, ".seat.open::UIStroke", 169, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(58, 71, 87),
	Transparency = 0,
})

rule(sheet, ".seat.movable:Hover", 209, {
	TextColor3 = Color3.fromRGB(96, 210, 242),
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(52, 66, 82),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".seat.movable:Hover::UIStroke", 209, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".seat-name", 80, {
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextTruncate = Enum.TextTruncate.AtEnd,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".bonus", 81, {
	AutomaticSize = Enum.AutomaticSize.XY,
})

rule(sheet, ".bonus::UIListLayout", 81, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".bonus::UIFlexItem", 81, {
	FlexMode = Enum.UIFlexMode.Custom,
	ShrinkRatio = 0,
})

rule(sheet, ".chip.step", 170, {
	Size = UDim2.new(0, 22, 0, 22),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".chip.step::UIPadding", 170, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 0),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 0),
})

rule(sheet, ".bonus-value", 82, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Center,
	TextWrapped = false,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.X,
})

rule(sheet, ".bonus-value::UISizeConstraint", 82, {
	MinSize = Vector2.new(44, 0),
	MaxSize = Vector2.new(math.huge, math.huge),
})

rule(sheet, ".bonus-value.up", 171, {
	TextColor3 = Color3.fromRGB(96, 224, 128),
	TextTransparency = 0,
})

rule(sheet, ".bonus-value.down", 172, {
	TextColor3 = Color3.fromRGB(238, 88, 74),
	TextTransparency = 0,
})

rule(sheet, ".room-actions", 83, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".room-actions::UIPadding", 83, {
	PaddingTop = UDim.new(0, 12),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 12),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".room-actions::UIListLayout", 83, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".status", 84, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".status.warning", 173, {
	TextColor3 = Color3.fromRGB(236, 184, 68),
	TextTransparency = 0,
})

rule(sheet, ".campaign-strip", 85, {
	Size = UDim2.new(1, 0, 0, 64),
	AutomaticSize = Enum.AutomaticSize.None,
})

do
	local r1 = rule(sheet, ".campaign-card", 86, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(1, 0, 1, 0),
		AutomaticSize = Enum.AutomaticSize.None,
		Position = UDim2.new(0.5, 0, 0.5, 0),
		AnchorPoint = Vector2.new(0.5, 0.5),
		BorderSizePixel = 0,
		ClipsDescendants = true,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		Rotation = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		Position = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		AnchorPoint = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".campaign-card::UIGradient", 86, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(47, 82, 99)), ColorSequenceKeypoint.new(0.6, Color3.fromRGB(34, 48, 60)), ColorSequenceKeypoint.new(1, Color3.fromRGB(31, 40, 51))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.117), NumberSequenceKeypoint.new(0.6, 0.144), NumberSequenceKeypoint.new(1, 0.15)}),
	Rotation = 0,
})

do
	local r1 = rule(sheet, ".campaign-card::UIStroke", 86, {
		Enabled = true,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		Thickness = 1,
		Color = Color3.fromRGB(96, 210, 242),
		Transparency = 0.5,
	})
	r1:SetPropertyTransitions({
		Color = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		Transparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

do
	local r1 = rule(sheet, ".campaign-card::UIScale", 86, nil)
	r1:SetPropertyTransitions({
		Scale = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".campaign-card:Hover, .campaign-card:Press", 174, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".campaign-card:Hover::UIGradient, .campaign-card:Press::UIGradient", 174, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(68, 118, 140)), ColorSequenceKeypoint.new(0.65, Color3.fromRGB(56, 79, 96)), ColorSequenceKeypoint.new(1, Color3.fromRGB(52, 66, 82))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.066), NumberSequenceKeypoint.new(0.65, 0.092), NumberSequenceKeypoint.new(1, 0.1)}),
	Rotation = 0,
})

rule(sheet, ".campaign-card:Hover::UIStroke, .campaign-card:Press::UIStroke", 174, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".campaign-card:Hover >> .campaign-card-glow, .campaign-card:Press >> .campaign-card-glow", 210, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".campaign-card:Hover >> .campaign-strip-title, .campaign-card:Press >> .campaign-strip-title", 211, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
})

rule(sheet, ".campaign-card:Hover >> .campaign-strip-texts::UIPadding, .campaign-card:Press >> .campaign-strip-texts::UIPadding", 212, {
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".campaign-card:Hover >> .campaign-card-chevron.lead, .campaign-card:Press >> .campaign-card-chevron.lead", 228, {
	Position = UDim2.new(0, 24, 0.5, 0),
	AnchorPoint = Vector2.new(0, 0.5),
	Rotation = 45,
})

rule(sheet, ".campaign-card:Hover >> .campaign-card-chevron.trail, .campaign-card:Press >> .campaign-card-chevron.trail", 229, {
	TextTransparency = 0,
	ImageTransparency = 0,
	GroupTransparency = 0,
	Position = UDim2.new(0, 12, 0.5, 0),
	AnchorPoint = Vector2.new(0, 0.5),
	Rotation = 45,
})

rule(sheet, ".campaign-card:Hover >> .campaign-card-chevron.trail >> .campaign-card-chevron-bar, .campaign-card:Press >> .campaign-card-chevron.trail >> .campaign-card-chevron-bar", 233, {
	BackgroundColor3 = Color3.fromRGB(96, 210, 242),
	BackgroundTransparency = 0.5,
})

rule(sheet, ".campaign-card.selected", 175, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".campaign-card.selected::UIGradient", 175, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(68, 118, 140)), ColorSequenceKeypoint.new(0.65, Color3.fromRGB(56, 79, 96)), ColorSequenceKeypoint.new(1, Color3.fromRGB(52, 66, 82))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.066), NumberSequenceKeypoint.new(0.65, 0.092), NumberSequenceKeypoint.new(1, 0.1)}),
	Rotation = 0,
})

rule(sheet, ".campaign-card.selected::UIStroke", 175, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".campaign-card.selected >> .campaign-card-glow", 213, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".campaign-card.selected >> .campaign-strip-title", 214, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
})

rule(sheet, ".campaign-card.selected >> .campaign-strip-texts::UIPadding", 215, {
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".campaign-card.selected >> .campaign-card-chevron.lead", 230, {
	Position = UDim2.new(0, 24, 0.5, 0),
	AnchorPoint = Vector2.new(0, 0.5),
	Rotation = 45,
})

rule(sheet, ".campaign-card.selected >> .campaign-card-chevron.trail", 231, {
	TextTransparency = 0,
	ImageTransparency = 0,
	GroupTransparency = 0,
	Position = UDim2.new(0, 12, 0.5, 0),
	AnchorPoint = Vector2.new(0, 0.5),
	Rotation = 45,
})

rule(sheet, ".campaign-card.selected >> .campaign-card-chevron.trail >> .campaign-card-chevron-bar", 234, {
	BackgroundColor3 = Color3.fromRGB(96, 210, 242),
	BackgroundTransparency = 0.5,
})

rule(sheet, ".campaign-card:Press", 176, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	AnchorPoint = Vector2.new(0.5, 0.5),
})

rule(sheet, ".campaign-card:Press::UIGradient", 176, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(50, 89, 106)), ColorSequenceKeypoint.new(0.6, Color3.fromRGB(35, 51, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(31, 40, 51))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.036), NumberSequenceKeypoint.new(0.6, 0.047), NumberSequenceKeypoint.new(1, 0.05)}),
	Rotation = 0,
})

rule(sheet, ".campaign-card:Press::UIScale", 176, {
	Scale = 0.97,
})

rule(sheet, ".campaign-card.launching >> .campaign-card-chevron.lead, .campaign-card.launching >> .campaign-card-chevron.trail", 232, {
	Position = UDim2.new(0, 56, 0.5, 0),
	AnchorPoint = Vector2.new(0, 0.5),
	Rotation = 45,
})

do
	local r1 = rule(sheet, ".campaign-card-glow", 87, {
		TextTransparency = 1,
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 1,
		ImageTransparency = 1,
		GroupTransparency = 1,
		Size = UDim2.new(0.45, 0, 1, 0),
		AutomaticSize = Enum.AutomaticSize.None,
		Position = UDim2.new(0, 0, 0, 0),
		ZIndex = 1,
		Interactable = false,
	})
	r1:SetPropertyTransitions({
		GroupTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		ImageTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		ScrollBarImageTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".campaign-card-glow::UIGradient", 87, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(96, 210, 242)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 0,
})

rule(sheet, ".campaign-card-edge", 88, {
	BackgroundColor3 = "$Accent",
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 3, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
	ZIndex = 2,
})

rule(sheet, ".campaign-card-content", 89, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
	ZIndex = 3,
})

rule(sheet, ".campaign-card-content::UIPadding", 89, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".campaign-card-content::UIListLayout", 89, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".campaign-card-sheen", 90, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 4,
	Interactable = false,
})

rule(sheet, ".campaign-card-sheen::UIGradient", 90, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 0)), ColorSequenceKeypoint.new(0.4, Color3.fromRGB(0, 0, 0)), ColorSequenceKeypoint.new(0.5, Color3.fromRGB(255, 255, 255)), ColorSequenceKeypoint.new(0.6, Color3.fromRGB(0, 0, 0)), ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 1), NumberSequenceKeypoint.new(0.4, 1), NumberSequenceKeypoint.new(0.5, 0.78), NumberSequenceKeypoint.new(0.6, 1), NumberSequenceKeypoint.new(1, 1)}),
	Rotation = 15,
})

rule(sheet, ".campaign-card-arrow", 91, {
	Size = UDim2.new(0, 48, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ClipsDescendants = true,
})

do
	local r1 = rule(sheet, ".campaign-card-chevron", 92, {
		Size = UDim2.new(0, 12, 0, 12),
		AutomaticSize = Enum.AutomaticSize.None,
		Position = UDim2.new(0, 0, 0.5, 0),
		AnchorPoint = Vector2.new(0, 0.5),
		Rotation = 45,
	})
	r1:SetPropertyTransitions({
		Rotation = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		Position = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		AnchorPoint = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		GroupTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		ImageTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		ScrollBarImageTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

do
	local r1 = rule(sheet, ".campaign-card-chevron::UIScale", 92, nil)
	r1:SetPropertyTransitions({
		Scale = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".campaign-card-chevron.lead", 177, {
	Position = UDim2.new(0, 16, 0.5, 0),
})

rule(sheet, ".campaign-card-chevron.trail", 178, {
	TextTransparency = 1,
	ImageTransparency = 1,
	GroupTransparency = 1,
	Position = UDim2.new(0, 4, 0.5, 0),
})

rule(sheet, ".campaign-card-chevron.trail >> .campaign-card-chevron-bar", 216, {
	BackgroundTransparency = 1,
})

do
	local r1 = rule(sheet, ".campaign-card-chevron-bar", 93, {
		BackgroundColor3 = "$Accent",
		BackgroundTransparency = 0,
		Position = UDim2.new(1, 0, 0, 0),
		AnchorPoint = Vector2.new(1, 0),
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".campaign-card-chevron-bar.top", 179, {
	Size = UDim2.new(1, 0, 0, 3),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".campaign-card-chevron-bar.side", 180, {
	Size = UDim2.new(0, 3, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".campaign-strip-texts", 94, {
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".campaign-strip-texts::UIListLayout", 94, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

do
	local r1 = rule(sheet, ".campaign-strip-texts::UIPadding", 94, nil)
	r1:SetPropertyTransitions({
		PaddingTop = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		PaddingRight = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		PaddingBottom = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		PaddingLeft = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
	})
end

do
	local r1 = rule(sheet, ".campaign-strip-title", 95, {
		TextSize = 16,
		Size = UDim2.new(1, 0, 0, 20),
		AutomaticSize = Enum.AutomaticSize.None,
	})
	r1:SetPropertyTransitions({
		TextColor3 = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		TextTransparency = TweenInfo.new(0.2, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		Rotation = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		Position = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
		AnchorPoint = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
	})
end

do
	local r1 = rule(sheet, ".campaign-strip-title::UIScale", 95, nil)
	r1:SetPropertyTransitions({
		Scale = TweenInfo.new(0.2, Enum.EasingStyle.Back, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".campaign-strip-progress", 96, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 16),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".campaign", 97, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".campaign::UIListLayout", 97, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".missions", 98, {
	Size = UDim2.new(0, 460, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".missions::UIListLayout", 98, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".mission-list", 99, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".mission-list::UIPadding", 99, {
	PaddingTop = UDim.new(0, 1),
	PaddingRight = UDim.new(0, 1),
	PaddingBottom = UDim.new(0, 1),
	PaddingLeft = UDim.new(0, 1),
})

rule(sheet, ".mission-list::UIListLayout", 99, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".mission-list::UIFlexItem", 99, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".mission-card", 100, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
	BorderSizePixel = 0,
})

rule(sheet, ".mission-card::UIGradient", 100, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(48, 56, 66)), ColorSequenceKeypoint.new(1, Color3.fromRGB(24, 30, 39))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.188), NumberSequenceKeypoint.new(1, 0.16)}),
	Rotation = 0,
})

rule(sheet, ".mission-card::UIPadding", 100, {
	PaddingTop = UDim.new(0, 12),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 12),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".mission-card::UIStroke", 100, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0.3,
})

rule(sheet, ".mission-card::UIListLayout", 100, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Top,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".mission-card.closed", 181, {
	TextTransparency = 0.45,
	BackgroundTransparency = 0.45,
	ImageTransparency = 0.45,
	GroupTransparency = 0.45,
})

rule(sheet, ".mission-card.closed::UIStroke", 181, {
	Transparency = 0.615,
})

rule(sheet, ".mission-card.closed >> .mission-title, .mission-card.closed >> .mission-number", 217, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
})

rule(sheet, ".mission-number", 101, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 28,
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(0, 44, 0, 36),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".mission-card.completed > .mission-number", 218, {
	TextColor3 = "$Gain",
	TextTransparency = 0,
})

rule(sheet, ".mission-details", 102, {
	Size = UDim2.new(0, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".mission-details::UIListLayout", 102, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Left,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".mission-details::UIFlexItem", 102, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
	ShrinkRatio = 1,
})

rule(sheet, ".mission-head", 103, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".mission-head::UIListLayout", 103, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".mission-title", 104, {
	TextSize = 16,
	Size = UDim2.new(0, 0, 0, 20),
	AutomaticSize = Enum.AutomaticSize.X,
})

rule(sheet, ".tag.done", 182, {
	TextColor3 = "$Gain",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.done::UIStroke", 182, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".tag.fresh", 183, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.fresh::UIStroke", 183, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".mission-description", 105, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 14,
	LineHeight = 1.35,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = true,
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".mission-unlocks", 106, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = true,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".button.play", 184, {
	Size = UDim2.new(0, 140, 0, 36),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".mission-buttons", 107, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".mission-buttons::UIListLayout", 107, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".campaign-actions", 108, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".campaign-actions::UIPadding", 108, {
	PaddingTop = UDim.new(0, 12),
})

rule(sheet, ".campaign-actions::UIListLayout", 108, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".campaign-status", 109, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = true,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".campaign-status::UISizeConstraint", 109, {
	MinSize = Vector2.new(0, 36),
	MaxSize = Vector2.new(math.huge, math.huge),
})

rule(sheet, ".campaign-status.warning", 185, {
	TextColor3 = Color3.fromRGB(236, 184, 68),
	TextTransparency = 0,
})

rule(sheet, ".unlocks", 110, {
	Size = UDim2.new(0, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".unlocks::UIListLayout", 110, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".unlocks::UIFlexItem", 110, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
	ShrinkRatio = 1,
})

rule(sheet, ".unlocks-note", 111, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(1, 0, 0, 16),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".unlock-groups", 112, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".unlock-groups::UIPadding", 112, {
	PaddingTop = UDim.new(0, 1),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 1),
	PaddingLeft = UDim.new(0, 1),
})

rule(sheet, ".unlock-groups::UIListLayout", 112, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 16),
})

rule(sheet, ".unlock-groups::UIFlexItem", 112, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".unlock-group", 113, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".unlock-group::UIListLayout", 113, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".unlock-grid", 114, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".unlock-grid::UIGridLayout", 114, {
	SortOrder = Enum.SortOrder.LayoutOrder,
	CellPadding = UDim2.new(0, 8, 0, 8),
	FillDirectionMaxCells = 4,
	CellSize = UDim2.new(0, 170, 0, 44),
})

rule(sheet, ".unlock", 115, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 44),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".unlock::UIGradient", 115, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(51, 59, 69)), ColorSequenceKeypoint.new(1, Color3.fromRGB(24, 31, 40))}),
	Transparency = NumberSequence.new({NumberSequenceKeypoint.new(0, 0.092), NumberSequenceKeypoint.new(1, 0.08)}),
	Rotation = 90,
})

rule(sheet, ".unlock::UIPadding", 115, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".unlock::UIStroke", 115, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0.2,
})

rule(sheet, ".unlock::UIListLayout", 115, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".unlock.locked", 186, {
	TextTransparency = 0.5,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.7,
	ImageTransparency = 0.5,
	GroupTransparency = 0.5,
	BorderSizePixel = 0,
})

rule(sheet, ".unlock.locked::UIStroke", 186, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0.75,
})

rule(sheet, ".unlock.locked >> .unlock-name", 219, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
})

rule(sheet, ".unlock.locked >> .unlock-subtitle", 220, {
	TextColor3 = Color3.fromRGB(79, 102, 128),
	TextTransparency = 0,
})

rule(sheet, ".unlock-names", 116, {
	Size = UDim2.new(0, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".unlock-names::UIListLayout", 116, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".unlock-names::UIFlexItem", 116, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
	ShrinkRatio = 1,
})

rule(sheet, ".unlock-name", 117, {
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextTruncate = Enum.TextTruncate.AtEnd,
	TextWrapped = false,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 17),
	AutomaticSize = Enum.AutomaticSize.None,
	ClipsDescendants = true,
})

rule(sheet, ".unlock-subtitle", 118, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextTruncate = Enum.TextTruncate.AtEnd,
	TextWrapped = false,
	Size = UDim2.new(1, 0, 0, 13),
	AutomaticSize = Enum.AutomaticSize.None,
	ClipsDescendants = true,
})

rule(sheet, ".unlock-lock", 119, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 9,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.X,
	BorderSizePixel = 0,
})

rule(sheet, ".unlock-lock::UIPadding", 119, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 4),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".unlock-lock::UIStroke", 119, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".unlock-lock::UIFlexItem", 119, {
	FlexMode = Enum.UIFlexMode.Custom,
	ShrinkRatio = 0,
})

rule(sheet, ".tabs", 120, {
	AutomaticSize = Enum.AutomaticSize.XY,
})

rule(sheet, ".tabs::UIListLayout", 120, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".chip.tab", 187, {
	Size = UDim2.new(0, 0, 0, 34),
	AutomaticSize = Enum.AutomaticSize.X,
})

rule(sheet, ".chip.tab::UIPadding", 187, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".chip.tab > .chip-label", 221, {
	TextSize = 12,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".skins-tab", 121, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".skins-tab::UIPadding", 121, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".skins-tab::UIListLayout", 121, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".skins-hint", 122, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = true,
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".skins-cards", 123, {
	BackgroundTransparency = 1,
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ScrollBarThickness = 8,
})

rule(sheet, ".skins-cards::UIFlexItem", 123, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

do
	local r1 = rule(sheet, ".skin-card", 124, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".skin-card::UIGradient", 124, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)), ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41))}),
	Rotation = 90,
})

rule(sheet, ".skin-card::UIPadding", 124, {
	PaddingTop = UDim.new(0, 12),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 12),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".skin-card::UIStroke", 124, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".skin-card::UIListLayout", 124, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".skin-card:Hover", 188, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".skin-card:Hover::UIStroke", 188, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".skin-card:Press", 189, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".skin-card:NonInteractable", 190, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".skin-card:NonInteractable::UIStroke", 190, {
	Transparency = 0.6,
})

rule(sheet, ".skin-card.equipped", 191, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".skin-card.equipped::UIGradient", 191, {
	Color = ColorSequence.new({ColorSequenceKeypoint.new(0, Color3.fromRGB(28, 127, 155)), ColorSequenceKeypoint.new(0.7, Color3.fromRGB(11, 106, 133)), ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 106, 133))}),
	Rotation = 0,
})

rule(sheet, ".skin-card.equipped::UIStroke", 191, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(96, 210, 242),
	Transparency = 0,
})

rule(sheet, ".skin-head", 125, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".skin-head::UIListLayout", 125, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".skin-name", 126, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 16,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 20),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".skin-name::UIFlexItem", 126, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".tag.developer", 192, {
	TextColor3 = "$Caution",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.developer::UIStroke", 192, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".skin-description", 127, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
	LineHeight = 1.3,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = true,
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".skin-extras", 128, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextWrapped = true,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".button.equip::UIFlexItem", 193, {
	ItemLineAlignment = Enum.ItemLineAlignment.End,
})

rule(sheet, ".microtransactions-tab", 129, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".microtransactions-tab::UIListLayout", 129, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".microtransactions-title", 130, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 24,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	AutomaticSize = Enum.AutomaticSize.XY,
})

rule(sheet, ".microtransactions-hint", 131, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 14,
	AutomaticSize = Enum.AutomaticSize.XY,
})

return sheet
