-- Generated by outlass 0.1.0 from src/lobby/client/stylesheets/lobby.scss. Do not edit by hand.

local sheet = Instance.new "StyleSheet"
sheet.Name = "lobby"
sheet:SetAttribute("Void", Color3.fromRGB(8, 11, 15))
sheet:SetAttribute("Steel", Color3.fromRGB(20, 26, 34))
sheet:SetAttribute("SteelRaised", Color3.fromRGB(31, 40, 51))
sheet:SetAttribute("SteelLit", Color3.fromRGB(52, 66, 82))
sheet:SetAttribute("Edge", Color3.fromRGB(78, 96, 118))
sheet:SetAttribute("Text", Color3.fromRGB(236, 244, 252))
sheet:SetAttribute("TextDim", Color3.fromRGB(186, 202, 220))
sheet:SetAttribute("TextFaint", Color3.fromRGB(146, 166, 188))
sheet:SetAttribute("Metal", Color3.fromRGB(196, 206, 220))
sheet:SetAttribute("Energy", Color3.fromRGB(255, 230, 64))
sheet:SetAttribute("Buildpower", Color3.fromRGB(126, 240, 154))
sheet:SetAttribute("Gain", Color3.fromRGB(96, 224, 128))
sheet:SetAttribute("Danger", Color3.fromRGB(238, 88, 74))
sheet:SetAttribute("Accent", Color3.fromRGB(96, 210, 242))
sheet:SetAttribute("Resurrect", Color3.fromRGB(176, 96, 240))
sheet:SetAttribute("Fight", Color3.fromRGB(255, 138, 64))

local function rule(parent: Instance, selector: string, priority: number?, properties: { [string]: any }?): StyleRule
	local r = Instance.new "StyleRule"
	r.Name = selector
	r.Selector = selector
	if priority then
		r.Priority = priority
	end
	if properties then
		r:SetProperties(properties)
	end
	r.Parent = parent
	return r
end

rule(sheet, "TextLabel, TextButton, TextBox", 0, {
	RichText = true,
	TextWrapped = true,
})

rule(
	sheet,
	"Frame, TextLabel, TextButton, TextBox, ImageLabel, ImageButton, ScrollingFrame, CanvasGroup, VideoFrame, ViewportFrame",
	0,
	{
		AutomaticSize = Enum.AutomaticSize.XY,
	}
)

rule(sheet, "Frame, TextButton, TextLabel", 1, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
})

rule(sheet, "Frame::UIStroke, TextButton::UIStroke, TextLabel::UIStroke", 1, {
	Enabled = false,
})

rule(sheet, "TextLabel, TextButton", 2, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Center,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".panel", 5, {
	TextTransparency = 0.03,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.03,
	ImageTransparency = 0.03,
	GroupTransparency = 0.03,
})

rule(sheet, ".panel::UIGradient", 5, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(52, 66, 82)),
		ColorSequenceKeypoint.new(0.03, Color3.fromRGB(52, 66, 82)),
		ColorSequenceKeypoint.new(0.04, Color3.fromRGB(20, 26, 34)),
		ColorSequenceKeypoint.new(0.55, Color3.fromRGB(20, 26, 34)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(1, 1, 2)),
	}),
	Rotation = 90,
})

rule(sheet, ".panel::UIPadding", 5, {
	PaddingTop = UDim.new(0, 16),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 16),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".rail", 6, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 2),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".rail::UIGradient", 6, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(96, 210, 242)),
		ColorSequenceKeypoint.new(0.55, Color3.fromRGB(96, 210, 242)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0)),
	}),
	Transparency = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 0),
		NumberSequenceKeypoint.new(0.55, 0),
		NumberSequenceKeypoint.new(1, 1),
	}),
	Rotation = 0,
})

rule(sheet, ".hazard", 7, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".hazard::UIGradient", 7, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.12, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.12, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(0.25, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(0.25, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.37, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.37, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(0.5, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(0.5, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.62, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.62, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(0.75, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(0.75, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.87, Color3.fromRGB(238, 88, 74)),
		ColorSequenceKeypoint.new(0.87, Color3.fromRGB(8, 11, 15)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(8, 11, 15)),
	}),
	Transparency = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 0.1),
		NumberSequenceKeypoint.new(0.12, 0.1),
		NumberSequenceKeypoint.new(0.25, 0.1),
		NumberSequenceKeypoint.new(0.37, 0.1),
		NumberSequenceKeypoint.new(0.5, 0.1),
		NumberSequenceKeypoint.new(0.62, 0.1),
		NumberSequenceKeypoint.new(0.75, 0.1),
		NumberSequenceKeypoint.new(0.87, 0.1),
		NumberSequenceKeypoint.new(1, 0.1),
	}),
	Rotation = -45,
})

rule(sheet, ".faint", 8, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
})

rule(sheet, ".metal", 9, {
	TextColor3 = "$Metal",
	TextTransparency = 0,
})

rule(sheet, ".energy", 10, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
})

rule(sheet, ".accent", 11, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
})

rule(sheet, ".heading", 12, {
	TextSize = 13,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".heading::UIStroke", 12, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.15,
})

rule(sheet, ".readout", 13, {
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".readout::UIStroke", 13, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.2,
})

rule(sheet, ".grow::UIFlexItem", 14, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, "ScrollingFrame", 3, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
	ClipsDescendants = true,
	ScrollingEnabled = true,
	ScrollingDirection = Enum.ScrollingDirection.Y,
})

rule(sheet, "ScrollingFrame::UIStroke", 3, {
	Enabled = false,
})

rule(sheet, "ImageLabel", 4, {
	BackgroundTransparency = 1,
	BorderSizePixel = 0,
})

rule(sheet, "ImageLabel::UIStroke", 4, {
	Enabled = false,
})

rule(sheet, ".accent-bar", 15, {
	BackgroundColor3 = "$Accent",
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 4, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".accent-bar.tall", 79, {
	Size = UDim2.new(0, 4, 0, 34),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".title-row", 16, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".title-row::UIListLayout", 16, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".badge", 17, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.X,
	BorderSizePixel = 0,
})

rule(sheet, ".badge::UIPadding", 17, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".badge::UIStroke", 17, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".tag", 18, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 16),
	AutomaticSize = Enum.AutomaticSize.X,
	BorderSizePixel = 0,
})

rule(sheet, ".tag::UIPadding", 18, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 4),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 4),
})

rule(sheet, ".tag::UIStroke", 18, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".tag.friends, .tag.you", 80, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.friends::UIStroke, .tag.you::UIStroke", 80, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".tag.host", 81, {
	TextColor3 = "$Energy",
	TextTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".tag.host::UIStroke", 81, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".seam", 19, {
	TextTransparency = 0.55,
	BackgroundColor3 = Color3.fromRGB(78, 96, 118),
	BackgroundTransparency = 0.55,
	ImageTransparency = 0.55,
	GroupTransparency = 0.55,
	Size = UDim2.new(1, 0, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
})

do
	local r1 = rule(sheet, ".button", 20, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 0, 0, 36),
		AutomaticSize = Enum.AutomaticSize.X,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".button::UIGradient", 20, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41)),
	}),
	Rotation = 90,
})

rule(sheet, ".button::UIPadding", 20, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 20),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 20),
})

rule(sheet, ".button::UIStroke", 20, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".button::UIListLayout", 20, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".button:Hover", 82, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button:Hover::UIStroke", 82, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".button:Press", 83, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".button:NonInteractable", 84, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".button.primary", 85, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".button.primary::UIGradient", 85, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(60, 183, 217)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(13, 125, 157)),
	}),
	Rotation = 90,
})

rule(sheet, ".button.primary::UIStroke", 85, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".button.primary:Hover", 110, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".button.locked, .button:NonInteractable", 86, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".button.join", 87, {
	Size = UDim2.new(0, 96, 0, 36),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".button-label", 21, {
	TextSize = 12,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

do
	local r1 = rule(sheet, ".chip", 22, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 0, 0, 30),
		AutomaticSize = Enum.AutomaticSize.X,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".chip::UIGradient", 22, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41)),
	}),
	Rotation = 90,
})

rule(sheet, ".chip::UIPadding", 22, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".chip::UIStroke", 22, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".chip::UIListLayout", 22, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".chip:Hover", 88, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip:Hover::UIStroke", 88, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".chip:Press", 89, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".chip:NonInteractable", 90, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".chip.active", 91, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.active::UIGradient", 91, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(43, 151, 181)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 109, 137)),
	}),
	Rotation = 90,
})

rule(sheet, ".chip.active::UIStroke", 91, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".chip.locked:Hover", 111, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.locked:Hover::UIStroke", 111, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".chip.locked.active:Hover", 117, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".chip.locked.active:Hover::UIGradient", 117, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(43, 151, 181)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(11, 109, 137)),
	}),
	Rotation = 90,
})

rule(sheet, ".chip.locked.active:Hover::UIStroke", 117, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".chip-label", 23, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
})

rule(sheet, ".chip.active > .chip-label", 112, {
	TextColor3 = "$Text",
	TextTransparency = 0,
})

rule(sheet, ".backdrop", 24, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
})

rule(sheet, ".backdrop-rail", 25, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 2),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0, 0, 0, 0),
})

rule(sheet, ".backdrop-rail::UIGradient", 25, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 0, 0)),
		ColorSequenceKeypoint.new(0.3, Color3.fromRGB(96, 210, 242)),
		ColorSequenceKeypoint.new(0.7, Color3.fromRGB(96, 210, 242)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 0, 0)),
	}),
	Transparency = NumberSequence.new({
		NumberSequenceKeypoint.new(0, 1),
		NumberSequenceKeypoint.new(0.3, 0),
		NumberSequenceKeypoint.new(0.7, 0),
		NumberSequenceKeypoint.new(1, 1),
	}),
	Rotation = 0,
})

rule(sheet, ".shell", 26, {
	Size = UDim2.new(0, 1240, 0, 720),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0.5, 0, 0.5, 0),
	AnchorPoint = Vector2.new(0.5, 0.5),
})

rule(sheet, ".shell::UIListLayout", 26, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".header", 27, {
	Size = UDim2.new(1, 0, 0, 64),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header::UIPadding", 27, {
	PaddingTop = UDim.new(0, 12),
	PaddingRight = UDim.new(0, 16),
	PaddingBottom = UDim.new(0, 12),
	PaddingLeft = UDim.new(0, 16),
})

rule(sheet, ".header::UIListLayout", 27, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".header-titles", 28, {
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".header-titles::UIListLayout", 28, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".header-title", 29, {
	TextSize = 18,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/Michroma.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 22),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header-title::UIStroke", 29, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Contextual,
	Thickness = 2,
	Color = Color3.fromRGB(8, 11, 15),
	Transparency = 0.15,
})

rule(sheet, ".header-subtitle", 30, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(1, 0, 0, 16),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".header-player", 31, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Right,
	AutomaticSize = Enum.AutomaticSize.XY,
})

rule(sheet, ".body", 32, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".body::UIFlexItem", 32, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".notice", 33, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.08,
	TextSize = 13,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	AutomaticSize = Enum.AutomaticSize.XY,
	Position = UDim2.new(0.5, 0, 1, -32),
	AnchorPoint = Vector2.new(0.5, 1),
	ZIndex = 10,
	BorderSizePixel = 0,
})

rule(sheet, ".notice::UIPadding", 33, {
	PaddingTop = UDim.new(0, 8),
	PaddingRight = UDim.new(0, 20),
	PaddingBottom = UDim.new(0, 8),
	PaddingLeft = UDim.new(0, 20),
})

rule(sheet, ".notice::UIStroke", 33, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".browser", 34, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".browser::UIListLayout", 34, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".lobby-columns", 35, {
	Size = UDim2.new(1, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-columns::UIPadding", 35, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".lobby-columns::UIListLayout", 35, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".column-name", 36, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".join-space", 37, {
	Size = UDim2.new(0, 96, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-list", 38, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-list::UIListLayout", 38, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".lobby-list::UIFlexItem", 38, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".lobby-row", 39, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 60),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-row::UIGradient", 39, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(40, 49, 59)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41)),
	}),
	Rotation = 90,
})

rule(sheet, ".lobby-row::UIPadding", 39, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

do
	local r1 = rule(sheet, ".lobby-row::UIStroke", 39, {
		Enabled = true,
		ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
		Thickness = 1,
		Color = Color3.fromRGB(78, 96, 118),
		Transparency = 0,
	})
	r1:SetPropertyTransitions({
		Color = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		Transparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".lobby-row::UIListLayout", 39, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".lobby-row:Hover", 92, {
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-row:Hover::UIStroke", 92, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".lobby-thumb", 40, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(0, 76, 0, 48),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-thumb::UIStroke", 40, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(37, 46, 57),
	Transparency = 0,
})

rule(sheet, ".lobby-thumb.blank", 93, {
	BackgroundTransparency = 1,
	Size = UDim2.new(0, 76, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".lobby-thumb.blank::UIStroke", 93, {
	Enabled = false,
})

rule(sheet, ".lobby-cell", 41, {
	TextXAlignment = Enum.TextXAlignment.Left,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.host::UIListLayout", 94, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".lobby-cell.host::UIFlexItem", 94, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".lobby-cell.mode", 95, {
	TextColor3 = "$Accent",
	TextTransparency = 0,
	Size = UDim2.new(0, 110, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.map", 96, {
	Size = UDim2.new(0, 190, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.map::UIListLayout", 96, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".lobby-cell.players", 97, {
	TextXAlignment = Enum.TextXAlignment.Right,
	Size = UDim2.new(0, 80, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".lobby-cell.players.full", 113, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
})

rule(sheet, ".lobby-cell.column-name", 98, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
})

rule(sheet, ".lobby-host", 42, {
	TextSize = 15,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 20),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-map-name, .lobby-map-size", 43, {
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(1, 0, 0, 18),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".lobby-map-size", 44, {
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
})

rule(sheet, ".empty", 45, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 15,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
	Size = UDim2.new(1, 0, 0, 120),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".room", 46, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".room::UIListLayout", 46, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".room-side", 47, {
	Size = UDim2.new(0, 524, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".room-side::UIListLayout", 47, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".map-panel", 48, {
	Size = UDim2.new(0, 704, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-panel::UIListLayout", 48, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".map-stage", 49, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 300),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".map-stage::UIGradient", 49, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(15, 20, 26)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(8, 11, 15)),
	}),
	Rotation = 90,
})

rule(sheet, ".map-stage::UIStroke", 49, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(37, 46, 57),
	Transparency = 0,
})

rule(sheet, ".map-fit", 50, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	Position = UDim2.new(0.5, 0, 0.5, 0),
	AnchorPoint = Vector2.new(0.5, 0.5),
	BorderSizePixel = 0,
})

rule(sheet, ".map-fit::UIStroke", 50, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".map-picture", 51, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 1,
})

rule(sheet, ".map-drawing", 52, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 2,
})

rule(sheet, ".map-grid", 53, {
	Size = UDim2.new(1, 0, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
	ZIndex = 3,
	Interactable = false,
})

rule(sheet, ".grid-line", 54, {
	TextTransparency = 0.78,
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0.78,
	ImageTransparency = 0.78,
	GroupTransparency = 0.78,
})

rule(sheet, ".grid-line.column", 99, {
	Size = UDim2.new(0, 1, 1, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".grid-line.row", 100, {
	Size = UDim2.new(1, 0, 0, 1),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".facts", 55, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".facts::UIListLayout", 55, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 20),
})

rule(sheet, ".fact", 56, {
	Size = UDim2.new(0, 84, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".fact::UIListLayout", 56, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 0),
})

rule(sheet, ".fact-label", 57, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".fact-value", 58, {
	TextSize = 17,
	TextXAlignment = Enum.TextXAlignment.Left,
	Size = UDim2.new(1, 0, 0, 22),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-description", 59, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 12,
	TextXAlignment = Enum.TextXAlignment.Left,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".map-grid-note", 60, {
	TextSize = 11,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
	Size = UDim2.new(1, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-list", 61, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-list::UIPadding", 61, {
	PaddingTop = UDim.new(0, 1),
	PaddingRight = UDim.new(0, 1),
	PaddingBottom = UDim.new(0, 1),
	PaddingLeft = UDim.new(0, 1),
})

rule(sheet, ".map-list::UIGridLayout", 61, {
	SortOrder = Enum.SortOrder.LayoutOrder,
	CellPadding = UDim2.new(0, 8, 0, 8),
	FillDirectionMaxCells = 4,
	CellSize = UDim2.new(0, 158, 0, 118),
})

rule(sheet, ".map-list::UIFlexItem", 61, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

do
	local r1 = rule(sheet, ".map-card", 62, {
		BackgroundColor3 = Color3.fromRGB(255, 255, 255),
		BackgroundTransparency = 0,
		Size = UDim2.new(0, 158, 0, 118),
		AutomaticSize = Enum.AutomaticSize.None,
		BorderSizePixel = 0,
	})
	r1:SetPropertyTransitions({
		BackgroundColor3 = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
		BackgroundTransparency = TweenInfo.new(0.1, Enum.EasingStyle.Quint, Enum.EasingDirection.Out),
	})
end

rule(sheet, ".map-card::UIGradient", 62, {
	Color = ColorSequence.new({
		ColorSequenceKeypoint.new(0, Color3.fromRGB(44, 53, 63)),
		ColorSequenceKeypoint.new(1, Color3.fromRGB(25, 32, 41)),
	}),
	Rotation = 90,
})

rule(sheet, ".map-card::UIPadding", 62, {
	PaddingTop = UDim.new(0, 6),
	PaddingRight = UDim.new(0, 6),
	PaddingBottom = UDim.new(0, 6),
	PaddingLeft = UDim.new(0, 6),
})

rule(sheet, ".map-card::UIStroke", 62, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".map-card::UIListLayout", 62, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	HorizontalAlignment = Enum.HorizontalAlignment.Center,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".map-card:Hover", 101, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card:Hover::UIStroke", 101, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".map-card:Press", 102, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
})

rule(sheet, ".map-card:NonInteractable", 103, {
	TextTransparency = 0.6,
	BackgroundTransparency = 0.6,
	ImageTransparency = 0.6,
	GroupTransparency = 0.6,
})

rule(sheet, ".map-card.active", 104, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.active::UIStroke", 104, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 2,
	Transparency = 0,
})

rule(sheet, ".map-card.locked:Hover", 114, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.locked:Hover::UIStroke", 114, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(78, 96, 118),
	Transparency = 0,
})

rule(sheet, ".map-card.locked.active:Hover", 118, {
	BackgroundColor3 = Color3.fromRGB(255, 255, 255),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".map-card.locked.active:Hover::UIStroke", 118, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 2,
	Transparency = 0,
})

rule(sheet, ".map-card-thumb", 63, {
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 70),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-card-name", 64, {
	TextSize = 13,
	TextTruncate = Enum.TextTruncate.AtEnd,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Bold, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 16),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-card-size", 65, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	TextSize = 10,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 13),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".map-card-size.crowded", 105, {
	TextColor3 = "$Danger",
	TextTransparency = 0,
})

rule(sheet, ".settings-panel", 66, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".settings-panel::UIListLayout", 66, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".group", 67, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".group::UIListLayout", 67, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".group-label", 68, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 10,
	TextXAlignment = Enum.TextXAlignment.Left,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(1, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".chips", 69, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".chips::UIListLayout", 69, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
	Wraps = true,
})

rule(sheet, ".seats-panel", 70, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".seats-panel::UIListLayout", 70, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".seats-panel::UIFlexItem", 70, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".sides", 71, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.None,
})

rule(sheet, ".sides::UIPadding", 71, {
	PaddingRight = UDim.new(0, 12),
})

rule(sheet, ".sides::UIListLayout", 71, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".sides::UIFlexItem", 71, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
})

rule(sheet, ".sides.split::UIListLayout", 106, {
	FillDirection = Enum.FillDirection.Horizontal,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".side", 72, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".side::UIListLayout", 72, {
	FillDirection = Enum.FillDirection.Vertical,
	SortOrder = Enum.SortOrder.LayoutOrder,
	Padding = UDim.new(0, 4),
})

rule(sheet, ".sides.split > .side", 115, {
	Size = UDim2.new(0, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".sides.split > .side::UIFlexItem", 115, {
	FlexMode = Enum.UIFlexMode.Custom,
	GrowRatio = 1,
	ShrinkRatio = 1,
})

rule(sheet, ".side-head", 73, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".side-head::UIListLayout", 73, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".side-count", 74, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 11,
	FontFace = Font.new("rbxasset://fonts/families/RobotoMono.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal),
	Size = UDim2.new(0, 0, 0, 14),
	AutomaticSize = Enum.AutomaticSize.X,
})

rule(sheet, ".seat", 75, {
	BackgroundColor3 = Color3.fromRGB(31, 40, 51),
	BackgroundTransparency = 0,
	Size = UDim2.new(1, 0, 0, 30),
	AutomaticSize = Enum.AutomaticSize.None,
	BorderSizePixel = 0,
})

rule(sheet, ".seat::UIPadding", 75, {
	PaddingTop = UDim.new(0, 0),
	PaddingRight = UDim.new(0, 8),
	PaddingBottom = UDim.new(0, 0),
	PaddingLeft = UDim.new(0, 8),
})

rule(sheet, ".seat::UIStroke", 75, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(48, 59, 72),
	Transparency = 0,
})

rule(sheet, ".seat::UIListLayout", 75, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 8),
})

rule(sheet, ".seat.you", 107, {
	BorderSizePixel = 0,
})

rule(sheet, ".seat.you::UIStroke", 107, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".seat.open", 108, {
	TextColor3 = "$TextFaint",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(8, 11, 15),
	BackgroundTransparency = 0.5,
	TextSize = 12,
	FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic),
	BorderSizePixel = 0,
})

rule(sheet, ".seat.open::UIStroke", 108, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Color = Color3.fromRGB(58, 71, 87),
	Transparency = 0,
})

rule(sheet, ".seat.movable:Hover", 116, {
	TextColor3 = "$Text",
	TextTransparency = 0,
	BackgroundColor3 = Color3.fromRGB(52, 66, 82),
	BackgroundTransparency = 0,
	BorderSizePixel = 0,
})

rule(sheet, ".seat.movable:Hover::UIStroke", 116, {
	Enabled = true,
	ApplyStrokeMode = Enum.ApplyStrokeMode.Border,
	Thickness = 1,
	Transparency = 0,
})

rule(sheet, ".seat-name", 76, {
	TextSize = 14,
	TextXAlignment = Enum.TextXAlignment.Left,
	TextTruncate = Enum.TextTruncate.AtEnd,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".room-actions", 77, {
	Size = UDim2.new(1, 0, 0, 0),
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".room-actions::UIPadding", 77, {
	PaddingTop = UDim.new(0, 12),
	PaddingRight = UDim.new(0, 12),
	PaddingBottom = UDim.new(0, 12),
	PaddingLeft = UDim.new(0, 12),
})

rule(sheet, ".room-actions::UIListLayout", 77, {
	FillDirection = Enum.FillDirection.Horizontal,
	SortOrder = Enum.SortOrder.LayoutOrder,
	VerticalAlignment = Enum.VerticalAlignment.Center,
	Padding = UDim.new(0, 12),
})

rule(sheet, ".status", 78, {
	TextColor3 = "$TextDim",
	TextTransparency = 0,
	TextSize = 13,
	AutomaticSize = Enum.AutomaticSize.Y,
})

rule(sheet, ".status.warning", 109, {
	TextColor3 = Color3.fromRGB(236, 184, 68),
	TextTransparency = 0,
})

return sheet
